import type { ActivityCategory, Person } from "./types";
import { portrait } from "./portrait";

const now = "2026-07-27T12:00:00.000Z";

function wikiImage(title: string) { return portrait(title); }

function p(
  id: string,
  name: string,
  activities: ActivityCategory[] = ["dubbing", "film", "series"],
  bio = "מדבב/ת ושחקן/ית ישראלי/ת — לפי קטגוריית מדבבים ישראלים בוויקיפדיה."
): Person {
  return {
    id, name, nicknames: [], tags: ["דיבוב", "ויקיפדיה"], activities, bio,
    wikipediaUrl: `https://he.wikipedia.org/wiki/${encodeURIComponent(name.replace(/ /g, "_"))}`,
    imageUrl: wikiImage(name), createdAt: now, updatedAt: now,
  };
}

/** מדבבים ישראלים מוויקיפדיה שלא היו במאגר (~356) */
export const WIKI_DUBBERS: Person[] = [
  p("mvtsy-abyb", "מוצי אביב"),
  p("asf-abydn", "אסף אבידן"),
  p("tvm-abny", "תום אבני"),
  p("abytl-abrgyl", "אביטל אברג'יל"),
  p("abytr-adyr", "אביתר אדיר"),
  p("rayh-admvny", "רעיה אדמוני"),
  p("chyym-adn", "חיים אדן"),
  p("shlvmyt-ahrvn", "שלומית אהרון"),
  p("mykh-avzyn-slyan", "מיכה אוזין סליאן"),
  p("mks-avlartsyk", "מקס אולארצ'יק"),
  p("avry-avmnvty", "אורי אומנותי"),
  p("yvbl-avpyr", "יובל אופיר"),
  p("yptch-avpyr", "יפתח אופיר"),
  p("karyn-avpyr", "קארין אופיר"),
  p("yryn-avrvn", "ירין אורון"),
  p("aby-avryh", "אבי אוריה"),
  p("dvrvn-avrn", "דורון אורן"),
  p("tly-avrn", "טלי אורן"),
  p("lyat-achyrvn", "ליאת אחירון"),
  p("rchl-atas", "רחל אטאס"),
  p("aprvn-atkyn", "עפרון אטקין"),
  p("aprt-gvsh", "אפרת גוש"),
  p("ayzy", "איזי"),
  p("aly-ayldys", "אלי אילדיס"),
  p("anytl-albchr", "אניטל אלבחר"),
  p("bny-aldr", "בני אלדר"),
  p("chn-alvn", "חן אלון"),
  p("gdy-altmn", "גדי אלטמן"),
  p("ant-alymlk", "ענת אלימלך"),
  p("alh-ptr", "אלה פטר"),
  p("chyym-almkys", "חיים אלמקיס"),
  p("gvry-alpy", "גורי אלפי"),
  p("mykalh-alkyn", "מיכאלה אלקין"),
  p("mykl-amdvrsky", "מיכל אמדורסקי"),
  p("tl-amyr", "טל אמיר"),
  p("gylt-ankvry", "גילת אנקורי"),
  p("alyazr-aplbvym", "אליעזר אפלבוים"),
  p("yhvdh-aprvny", "יהודה אפרוני"),
  p("ady-ard", "עדי ארד"),
  p("abygyl-aryaly", "אביגיל אריאלי"),
  p("shyry-artsy", "שירי ארצי"),
  p("chrvt-ashknzy", "חרות אשכנזי"),
  p("ady-ashknzy", "עדי אשכנזי"),
  p("kvby-ashl", "קובי אשל"),
  p("asf-ashtr", "אסף אשתר"),
  p("dvdv-bavknr", "דודו באוכנר"),
  p("gyh-bar-gvrbyts", "גיה באר גורביץ'"),
  p("sar-bdyshy", "סער בדישי"),
  p("agm-bvchbvt", "אגם בוחבוט"),
  p("avr-bvtbvl", "אור בוטבול"),
  p("ady-byty", "עדי ביטי"),
  p("yvbl-byndr", "יובל בינדר"),
  p("rvny-blyts", "רוני בליץ"),
  p("tl-blkrvbyts", "טל בלכרוביץ'"),
  p("shmyl-bn-ary", "שמיל בן ארי"),
  p("zyl-bn-dvd", "ז'יל בן-דוד"),
  p("dvry-bn-zab", "דורי בן זאב"),
  p("lbnt-bn-chmv", "לבנת בן-חמו"),
  p("tly-bn-yvsf", "טלי בן יוסף"),
  p("dbyr-bndk", "דביר בנדק"),
  p("nykv-br", "ניקו בר"),
  p("yvab-br-lb", "יואב בר-לב"),
  p("rvay-br-ntn", "רועי בר-נתן"),
  p("shlmh-br-shbyt", "שלמה בר-שביט"),
  p("rvsln-brbnvb", "רוסלן ברבנוב"),
  p("nmrvd-brgmn", "נמרוד ברגמן"),
  p("rmy-brvk", "רמי ברוך"),
  p("shgya-bryytnr", "שגיא ברייטנר"),
  p("mvty-brkan", "מוטי ברכאן"),
  p("tvny-brmn", "טוני ברמן"),
  p("lyrvn-brns", "לירון ברנס"),
  p("mykv-gmal", "מיקו ג'מאל"),
  p("ayty-grvpy", "איתי ג'רופי"),
  p("adm-gbay", "אדם גבאי"),
  p("lytl-gbay", "ליטל גבאי"),
  p("rynt-gbay", "רינת גבאי"),
  p("dvyt-gbysh", "דוית גביש"),
  p("avry-gbryal", "אורי גבריאל"),
  p("mrym-gbryaly", "מרים גבריאלי"),
  p("rn-gvath", "רן גואטה"),
  p("chnn-gvldblt", "חנן גולדבלט"),
  p("yal-gvldmn", "יעל גולדמן"),
  p("yshral-gvryvn", "ישראל גוריון"),
  p("ayly-gvrlytsky", "אילי גורליצקי"),
  p("dvdy-gzyt", "דודי גזית"),
  p("glyt-gyat", "גלית גיאת"),
  p("tvmr-glrvn", "תומר גלרון"),
  p("ysmyn-gmlyal", "יסמין גמליאל"),
  p("ayln-gnny", "אילן גנני"),
  p("yvsy-grbr", "יוסי גרבר"),
  p("aytn-grynbrg", "איטן גרינברג"),
  p("aylnyt-grshvn", "אילנית גרשון"),
  p("ayryt-dgn", "עירית דגן"),
  p("rvny-dvany", "רוני דואני"),
  p("yvbl-dvr", "יובל דור"),
  p("dynh-dvrvn", "דינה דורון"),
  p("dvdv-dvtn", "דודו דותן"),
  p("lyavr-dtavkr", "ליאור דטאוקר"),
  p("ntn-dtnr", "נתן דטנר"),
  p("mvty-dyknh", "מוטי דיכנה"),
  p("rvny-dlvmy", "רוני דלומי"),
  p("chgyt-dsbrg", "חגית דסברג"),
  p("drvr-tplytsky", "דרור טפליצקי"),
  p("dklh-hdr", "דקלה הדר"),
  p("avry-hvkmn", "אורי הוכמן"),
  p("yvab-hyymn", "יואב היימן"),
  p("sy-hyymn", "סי היימן"),
  p("almvg-hyrsh", "אלמוג הירש"),
  p("shavly-hlvy", "שאולי הלוי"),
  p("mykal-hngby", "מיכאל הנגבי"),
  p("bny-hndl", "בני הנדל"),
  p("nchmh-hndl", "נחמה הנדל"),
  p("rvbrt-hnyg", "רוברט הניג"),
  p("azra-hs", "עזרא הס"),
  p("avry-hr-lb", "אורי הר-לב"),
  p("lyat-hr-lb", "ליאת הר לב"),
  p("myykl-hrpz", "מייקל הרפז"),
  p("dydy-hrry", "דידי הררי"),
  p("amnvn-vvlf", "אמנון וולף"),
  p("amy-vyynbrg", "עמי ויינברג"),
  p("tl-vyys-shchkn", "טל וייס (שחקן)"),
  p("rvay-vyynbrg", "רועי ויינברג"),
  p("shrh-vynv-alad", "שרה וינו-אלעד"),
  p("aby-mayr-vanvnv", "אבי מאיר וענונו"),
  p("ant-vksmn", "ענת וקסמן"),
  p("ddy-zhr", "דדי זהר"),
  p("lyavr-zvhr", "ליאור זוהר"),
  p("shy-zvrnytsr", "שי זורניצר"),
  p("aymry-zyv", "אימרי זיו"),
  p("rann-zyv", "רענן זיו"),
  p("gya-zyydmn", "גיא זיידמן"),
  p("dnyal-zylbrshtyyn-zmr", "דניאל זילברשטיין (זמר)"),
  p("ady-zynv", "עדי זינו"),
  p("nytsn-zytsr", "ניצן זיצר"),
  p("avry-zltsmn", "אורי זלצמן"),
  p("rvytl-zltsmn", "רויטל זלצמן"),
  p("yvbl-zmyr", "יובל זמיר", ["dubbing", "film", "series", "stage", "musical"], "יובל זמיר (1963–2011) היה שחקן תיאטרון וקולנוע, מדבב, במאי וזמר אופרה ישראלי. דיבב בין השאר בפינוקיו, סינדרלה, נסיך מצרים ובאג לייף. מקור: ויקיפדיה."),
  p("chyym-znaty", "חיים זנאתי"),
  p("almh-zk", "עלמה זק"),
  p("chn-chgy", "חן חגי"),
  p("chvby-star", "חובי סטאר"),
  p("aprh-chzh", "עפרה חזה"),
  p("mlaky-chzkyh", "מלאכי חזקיה"),
  p("yoni-chen", "יוני חן", ["dubbing", "film", "series", "stage"], "יוני חן (1953–1995) היה שחקן, במאי, בובנאי ומדבב ישראלי. דיבב והפעיל את בץ ב„פרפר נחמד”, הקים את אולפן הדיבוב אולפנטו, ושיחק ב„הלהקה”, „דיזנגוף 99” ו„חמש חמש”. מקור: ויקיפדיה."),
  p("shchr-chsvn", "שחר חסון"),
  p("shchr-tbvk", "שחר טבוך"),
  p("tvbyh-tvvyg", "טוביה טוויג"),
  p("yvsy-tvldv", "יוסי טולדו"),
  p("chyym-tvpvl", "חיים טופול"),
  p("shrvn-tyykr", "שרון טייכר"),
  p("ayty-tyran", "איתי טיראן"),
  p("shmvlyk-tna", "שמוליק טנא"),
  p("dvry-tpr", "דורי טפר"),
  p("gayh-travb", "גאיה טראוב"),
  p("amy-travb", "עמי טראוב"),
  p("yshral-tryystmn", "ישראל טרייסטמן"),
  p("abyb-trnr", "אביב טרנר"),
  p("yvbl-ynay", "יובל ינאי"),
  p("mykl-ynay", "מיכל ינאי"),
  p("tslylh-ynay", "צלילה ינאי"),
  p("avry-ynyb", "אורי יניב"),
  p("rvyt-yakb", "רוית יעקב"),
  p("aby-yph", "אבי יפה"),
  p("yvab-ypt", "יואב יפת"),
  p("aby-ykyr", "אבי יקיר"),
  p("yrvn-lvy-sbg", "ירון לוי סבג"),
  p("avryt-yrvn", "אורית ירון"),
  p("hlnh-yrlvbh", "הלנה ירלובה"),
  p("shchr-yshy", "שחר ישי"),
  p("avry-kbyry", "אורי כבירי"),
  p("albrt-khn", "אלברט כהן"),
  p("yakb-khn-shchkn", "יעקב כהן (שחקן)"),
  p("lyn-khn", "לין כהן"),
  p("lny-khn", "לני כהן"),
  p("nvryt-khn", "נורית כהן"),
  p("shmavn-khn-mdbb", "שמעון כהן (מדבב)"),
  p("shny-khn", "שני כהן"),
  p("ant-kvgn", "ענת כוגן"),
  p("yhvntn-kys-lb", "יהונתן כיס-לב"),
  p("lyavr-klpvn", "ליאור כלפון"),
  p("lyrvn-krkvkly", "לירון כרקוקלי"),
  p("myky-lavn", "מיקי לאון"),
  p("ady-lb", "עדי לב"),
  p("stpn-lgr", "סטפן לגר"),
  p("avry-lvy-shchkn", "אורי לוי (שחקן)"),
  p("mvmy-lvy", "מומי לוי"),
  p("mykl-lvy", "מיכל לוי"),
  p("alchy-lvyt", "אלחי לויט"),
  p("aly-lvlay", "אלי לולאי"),
  p("aytn-lvndnr", "איתן לונדנר"),
  p("shmryt-lvstyg", "שמרית לוסטיג"),
  p("anbl-lvry", "ענבל לורי"),
  p("ayln-lybvbyts-shchkn", "אילן ליבוביץ (שחקן)"),
  p("mayh-lbny", "מאיה לבני"),
  p("alvn-lytbk", "אלון ליטבק"),
  p("dny-lytny", "דני ליטני"),
  p("avry-lyyzrvbyts", "אורי לייזרוביץ'"),
  p("shyrly-lylv", "שירלי לילו"),
  p("kynrt-lymvny", "כינרת לימוני"),
  p("myh-lndsmn", "מיה לנדסמן"),
  p("dvn-lny-gbay", "דון לני-גבאי"),
  p("chnh-lslav", "חנה לסלאו"),
  p("bvby-lks", "בובי לקס"),
  p("yval-lrnr-zmr", "יואל לרנר (זמר)"),
  p("dny-lshmn", "דני לשמן"),
  p("ant-mgn-shbv", "ענת מגן-שבו"),
  p("mykl-mvktr", "מיכל מוכתר"),
  p("rvby-mvskvbyts", "רובי מוסקוביץ'"),
  p("aryh-mvskvnh", "אריה מוסקונה"),
  p("abrhm-mvr", "אברהם מור"),
  p("tsypy-mvr", "ציפי מור"),
  p("gvr-mvrd", "גור מורד"),
  p("avdlyh-mvrh-mtlvn", "אודליה מורה-מטלון"),
  p("dnyal-mvrsht", "דניאל מורשת"),
  p("amyt-mvrsht", "עמית מורשת"),
  p("kvby-mydn", "קובי מידן"),
  p("mayh-mytlpvnkt", "מאיה מיטלפונקט"),
  p("mytl-mykaly", "מיטל מיכאלי"),
  p("rbkh-mykaly", "רבקה מיכאלי"),
  p("br-mynyaly", "בר מיניאלי"),
  p("tyylvr-mlkvb", "טיילור מלכוב"),
  p("avdd-mnstr", "עודד מנסטר"),
  p("yrvn-chy-mnshh", "ירון חי מנשה"),
  p("krmyt-msylty", "כרמית מסילתי"),
  p("amnvn-mskyn", "אמנון מסקין"),
  p("ayrys-mrtynz", "איריס מרטינז"),
  p("dnh-mrmvr", "דנה מרמור"),
  p("rvny-ndlr", "רוני נדלר"),
  p("shy-nvblmn", "שי נובלמן"),
  p("ytschk-nvy", "יצחק נוי"),
  p("tschy-nvy", "צחי נוי"),
  p("gavlh-nvny", "גאולה נוני"),
  p("ayyl-nchmyas", "אייל נחמיאס"),
  p("dvdv-nyb", "דודו ניב"),
  p("ant-nyb", "ענת ניב"),
  p("shrvnh-nstvbyts", "שרונה נסטוביץ'"),
  p("gya-ntyb", "גיא נתיב"),
  p("ayryt-ntn-bndk", "עירית נתן בנדק"),
  p("gyl-ntnzvn", "גיל נתנזון"),
  p("ntn-ntnzvn", "נתן נתנזון"),
  p("br-sbyr", "בר סביר"),
  p("lvrn-sbyr", "לורן סביר"),
  p("gyl-sgl-shchkn", "גיל סגל (שחקן)"),
  p("yvbl-sgl-1980", "יובל סגל (1980)"),
  p("yvsy-sgl", "יוסי סגל"),
  p("shlmh-sdn", "שלמה סדן"),
  p("hylh-svrgvn-pyshr", "הילה סורג'ון פישר"),
  p("aytsyk-syydvf", "איציק סיידוף"),
  p("abrhm-slktr", "אברהם סלקטר"),
  p("dvdyk-smdr", "דודיק סמדר"),
  p("dnh-smv", "דנה סמו"),
  p("gyl-ssvbr", "גיל ססובר"),
  p("shshy-sad", "ששי סעד"),
  p("yvly-skr", "יולי סקר"),
  p("dvr-srvgv", "דור סרוגו"),
  p("gl-sry", "גל סרי"),
  p("mty-sry", "מתי סרי"),
  p("shryt-sry", "שרית סרי"),
  p("shavl-azr", "שאול עזר"),
  p("ysmyn-ayvn", "יסמין עיון"),
  p("lyanh-ayvn", "ליאנה עיון"),
  p("mykal-aynb", "מיכאל עינב"),
  p("tmr-amyt-yvsf", "תמר עמית יוסף"),
  p("yal-amyt", "יעל עמית"),
  p("ayryt-anby", "עירית ענבי"),
  p("avmr-atsyvn", "עומר עציון"),
  p("ant-atsmvn", "ענת עצמון"),
  p("aryk-asht", "אריק עשת"),
  p("myly-asht", "מילי עשת"),
  p("lyavr-pavkr", "ליאור פאוקר"),
  p("aryal-pvrmn", "אריאל פורמן"),
  p("avdd-pz", "עודד פז"),
  p("myrb-pldmn", "מירב פלדמן"),
  p("aby-pnyny", "אבי פניני"),
  p("abytl-pstrnk", "אביטל פסטרנק"),
  p("bn-prg", "בן פרג'"),
  p("kvby-prg", "קובי פרג'"),
  p("namy-prvmvbyts", "נעמי פרומוביץ'"),
  p("yryn-pry", "ירין פרי"),
  p("gma-pryd", "גמא פריד"),
  p("dlyh-prydlnd", "דליה פרידלנד"),
  p("yhvykyn-prydlndr", "יהויכין פרידלנדר"),
  p("gya-prydmn", "גיא פרידמן"),
  p("gya-rvshynyak", "גיא רושיניאק"),
  p("tl-prydmn", "טל פרידמן"),
  p("nyr-prydmn", "ניר פרידמן"),
  p("dnh-prydr", "דנה פרידר"),
  p("pz-prl", "פז פרל"),
  p("nam-prnk", "נעם פרנק"),
  p("avmr-prnkl", "עומר פרנקל"),
  p("mshh-prstr", "משה פרסטר"),
  p("aryh-tsrnr", "אריה צ'רנר"),
  p("avral-tsbry", "אוראל צברי"),
  p("dvr-tsvygnbvm", "דור צויגנבום"),
  p("yvab-tsvkr", "יואב צוקר"),
  p("shry-tsvryal", "שרי צוריאל"),
  p("ant-tschvr", "ענת צחור"),
  p("yvab-tspyr", "יואב צפיר"),
  p("yvsy-kants", "יוסי קאנץ"),
  p("aty-kary", "אתי קארי"),
  p("myyh-kdvsh", "מייה קדוש"),
  p("kvvamy", "קוואמי"),
  p("an-kvnvpny", "אן קונופני"),
  p("bvaz-kvnpvrty", "בועז קונפורטי"),
  p("asty-kvsvbytsky", "אסתי קוסוביצקי"),
  p("asf-kvrmn", "אסף קורמן"),
  p("yvtm-kvshnyr", "יותם קושניר"),
  p("dn-kyzlr", "דן קיזלר"),
  p("mykal-kyyt", "מיכאל קייט"),
  p("tmr-kynn", "תמר קינן"),
  p("mshy-klynshtyyn", "משי קלינשטיין"),
  p("adm-knt", "אדם קנת"),
  p("gyvra-knt", "גיורא קנת"),
  p("astr-aty-kstrv", "אסתר אתי קסטרו"),
  p("gyl-kptn", "גיל קפטן"),
  p("yal-krvvn", "יעל קרוון"),
  p("drvr-krn", "דרור קרן"),
  p("aly-krn-asf", "אלי קרן-אסף"),
  p("nah-kshpytsky", "נעה קשפיצקי"),
  p("rvay-rbyb", "רועי רביב"),
  p("dvrvn-rbyts", "דורון רביץ"),
  p("aydv-rvznbrg", "עידו רוזנברג"),
  p("amry-rvnn-shdrn-rdyv", "עמרי רונן (שדרן רדיו)"),
  p("nmrvd-rshf", "נמרוד רשף"),
  p("shny-shavly", "שני שאולי"),
  p("ayh-shba", "איה שבא"),
  p("syvn-shbyt", "סיון שביט"),
  p("dny-shgb", "דני שגב"),
  p("ygal-shdh", "יגאל שדה"),
  p("amvs-shvb", "עמוס שוב"),
  p("lytl-shvvrts", "ליטל שוורץ"),
  p("tsbykh-shvvrtsbrg", "צביקה שוורצברג"),
  p("tvm-shvvrtsbrg", "תום שוורצברג"),
  p("mvly-shvlmn", "מולי שולמן"),
  p("shrvn-shchl", "שרון שחל"),
  p("avhd-shchr", "אוהד שחר"),
  p("dny-shtg", "דני שטג"),
  p("abyshy-shtryt", "אבישי שטרית"),
  p("namh-shtryt", "נעמה שטרית"),
  p("gylyh-shtrn", "גיליה שטרן"),
  p("ayryt-shylh", "עירית שילה"),
  p("apr-shktr", "עפר שכטר"),
  p("nysv-shlyv", "ניסו שליו"),
  p("glad-shmvaly-shchkn", "גלעד שמואלי (שחקן)"),
  p("ytschk-shmavny", "יצחק שמעוני"),
  p("gdavn-shmr", "גדעון שמר"),
  p("shvshyk-shny", "שושיק שני"),
  p("nyr-shayby", "ניר שעיבי"),
  p("nta-shpyglmn", "נטע שפיגלמן"),
  p("shpyth-zmrt", "שפיטה (זמרת)"),
  p("tvbl-shpyr", "תובל שפיר"),
  p("lymvr-shpyra", "לימור שפירא"),
  p("namh-shpyra", "נעמה שפירא"),
  p("ravbn-shpr", "ראובן שפר"),
  p("arz-shpryr", "ארז שפריר"),
  p("shry-zmrt", "שרי (זמרת)"),
  p("vyky-tbvr", "ויקי תבור"),
  p("alyanh-tdhr", "אליאנה תדהר"),
  p("dn-tvrn", "דן תורן"),
  p("amvs-tmm", "עמוס תמם"),
];
