import type { ActivityCategory, Credit, Person, Production } from "./types";
import { portrait } from "./portrait";

const now = "2026-07-23T16:00:00.000Z";

function p(
  id: string,
  name: string,
  activities: ActivityCategory[],
  bio: string,
  also?: string,
  extra: Partial<Person> = {}
): Person {
  return {
    id,
    name,
    nicknames: extra.nicknames || [],
    tags: extra.tags || ["דיבוב"],
    activities,
    bio,
    nameOriginal: also || extra.nameOriginal,
    birthDate: extra.birthDate,
    deathDate: extra.deathDate,
    imageUrl: extra.imageUrl || portrait(name, also),
    createdAt: now,
    updatedAt: now,
  };
}

function prod(
  id: string,
  title: string,
  year: number,
  kind: Production["kind"],
  summary: string,
  genres: string[],
  extra: Partial<Production> = {}
): Production {
  return {
    id,
    title,
    year,
    kind,
    summary,
    genres,
    originalTitle: extra.originalTitle,
    endYear: extra.endYear,
    channel: extra.channel,
    studio: extra.studio,
    dubbingStudio: extra.dubbingStudio,
    imageUrl: extra.imageUrl || portrait(extra.originalTitle || title, title),
    createdAt: now,
    updatedAt: now,
  };
}

export const WAVE2_PEOPLE: Person[] = [
  p("sharon-cohen", "שרון כהן", ["dubbing", "film", "series", "musical"], "מדבב, במאי דיבוב ומתרגם מרכזי בדיבוב העברי.", "Sharon Cohen (voice actor)", { tags: ["דיבוב", "בימוי דיבוב"] }),
  p("kobi-likverman", "קובי ליקורמן", ["dubbing", "film", "series"], "מדבב ישראלי פורה באנימציה ובהפקות ילדים.", "Kobi Likverman"),
  p("daniel-magon", "דניאל מגון", ["dubbing", "film", "series", "festival", "stage"], "שחקן ומדבב. דיבב מגיל צעיר והשתתף בפסטיגל.", "Daniel Magon", { birthDate: "1988-03-15", tags: ["דיבוב", "פסטיגל"] }),
  p("yonatan-magon", "יהונתן מגון", ["dubbing", "series", "film"], "מדבב ושחקן ממשפחת המגונים.", "Yonatan Magon"),
  p("liron-lev", "לירון לב", ["dubbing", "film", "series", "musical"], "מדבב וזמר. דיבב דמויות מרכזיות בדיסני.", "Liron Lev", { tags: ["דיבוב", "דיסני"] }),
  p("tuvia-tsafir", "טוביה צפיר", ["dubbing", "series", "film", "stage", "cassette"], "שחקן, קומיקאי ומדבב אייקוני.", "Tuvia Tzafir", { tags: ["דיבוב", "קומדיה"] }),
  p("zipi-shavit", "ציפי שביט", ["festival", "performance", "cassette", "film", "series"], "כוכבת ילדים ישראלית — קלטות, מופעים וטלוויזיה.", "Tzipi Shavit", { tags: ["ילדים", "קלטות"] }),
  p("noa-kirel-w2", "נועה קירל", ["performance", "musical", "festival", "film", "series"], "זמרת, שחקנית וכוכבת במה.", "Noa Kirel", { tags: ["זמרת", "נוער"] }),
  p("anna-zak-w2", "אנה זק", ["performance", "series", "festival", "film"], "זמרת ושחקנית נוער.", "Anna Zak", { tags: ["נוער"] }),
  p("yuval-hamvulbal-w2", "יובל המבולבל", ["festival", "performance", "cassette", "series", "hosting"], "יוצר וכוכב ילדים — מופעים, סדרות וקלטות.", "Yuval Hamevulbal", { tags: ["ילדים"] }),

  p("oran-tal", "אורן טל", ["dubbing", "film", "series"], "מדבב ישראלי בהפקות אנימציה."),
  p("talya-barkai", "טליה ברקאי", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("hilla-priel", "הילה פריאל", ["dubbing", "series", "film"], "מדבבת בהפקות ילדים ונוער."),
  p("omri-dreznin", "עומרי דרזנין", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("shaked-levy", "שקד לוי", ["dubbing", "series", "film", "musical"], "מדבבת וזמרת."),
  p("ido-mosseri-w2", "עידו מוסרי", ["dubbing", "film", "series", "festival", "stage"], "שחקן, מדבב וכוכב ילדים.", "Ido Mosseri", { tags: ["ילדים", "דיבוב"] }),
  p("maya-shoef", "מאיה שואף", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("gal-levin", "גל לוין", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("nofar-cohen", "נופר כהן", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("yonatan-hashiloni", "יונתן השילוני", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("adi-bianko", "עדי ביאנקו", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("roy-maman", "רועי ממן", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("shira-gavrielov", "שירה גבריאלוב", ["dubbing", "series", "film", "musical"], "מדבבת וזמרת."),
  p("itay-zaidman", "איתי זיידמן", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("yael-ben-aryeh", "יעל בן אריה", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("amit-farkash-w2", "עמית פרקש", ["series", "film", "musical", "performance"], "שחקנית וזמרת — נוער ומחזמר.", "Amit Farkash", { tags: ["מחזמר", "נוער"] }),
  p("yon-tumarkin-w2", "יון תומרקין", ["series", "film", "stage", "dubbing"], "שחקן שגדל ככוכב ילדים/נוער.", "Yon Tumarkin"),
  p("adi-himelbloy-w2", "עדי הימלבלוי", ["series", "film", "stage"], "שחקנית ישראלית, החלה כשחקנית נוער.", "Adi Himelbloy"),
  p("agam-rodberg", "אגם רודברג", ["series", "film", "stage", "festival", "performance"], "שחקנית טלוויזיה וקולנוע (גם אגם גולדברג).", "Agam Rudberg", { nicknames: ["אגם גולדברג", "Agam Goldberg"], tags: ["משחק", "נוער"] }),
  p("lihi-kornowski", "ליהי קורנובסקי", ["series", "film", "stage"], "שחקנית ישראלית.", "Lihi Kornowski"),
  p("daniel-gad", "דניאל גד", ["series", "film", "stage"], "שחקן ישראלי.", "Daniel Gad"),
  p("shira-katzenellenbogen", "שירה קצנלנבוגן", ["series", "film", "stage"], "שחקנית ישראלית."),
  p("michael-alinor", "מיכאל אלוני", ["series", "film", "stage"], "שחקן ישראלי.", "Michael Aloni"),
  p("rotum-sela", "רותם סלע", ["series", "film", "hosting"], "שחקנית ומנחה.", "Rotem Sela"),
  p("moshe-ashkenazi", "משה אשכנזי", ["series", "film", "stage"], "שחקן ישראלי.", "Moshe Ashkenazi"),
  p("ninet-tayeb-w2", "נינט טייב", ["musical", "performance", "film", "series"], "זמרת ושחקנית.", "Ninet Tayeb", { tags: ["מחזמר"] }),
  p("harel-skaat-w2", "הראל סקעת", ["musical", "performance", "stage"], "זמר ושחקן מחזמר.", "Harel Skaat", { tags: ["מחזמר"] }),
  p("shiri-mimon-w2", "שירי מימון", ["musical", "performance", "stage"], "זמרת ומחזמרים.", "Shiri Maimon", { tags: ["מחזמר"] }),
  p("rita-w2", "ריטה", ["musical", "performance", "stage", "film"], "זמרת ישראלית אייקונית.", "Rita (Israeli singer)", { tags: ["זמרת"] }),
  p("gidi-gov-w2", "גידי גוב", ["musical", "performance", "series", "hosting", "film"], "זמר, שחקן ומנחה.", "Gidi Gov"),
  p("yardena-arazi-w2", "ירדנה ארזי", ["musical", "performance", "hosting", "festival"], "זמרת ומנחה.", "Yardena Arazi"),
  p("svika-pick-w2", "צביקה פיק", ["musical", "performance", "festival"], "זמר ויוצר.", "Svika Pick", { deathDate: "2022-08-14" }),
  p("michal-haqtana", "מיכל הקטנה", ["festival", "performance", "cassette", "series"], "כוכבת ילדים.", "Michal HaKtana", { tags: ["ילדים"] }),
  p("mariko-w2", "מריקו", ["festival", "performance", "cassette", "series"], "כוכבת ילדים ישראלית.", "Mariko", { tags: ["ילדים"] }),
  p("uchi-w2", "אוחי", ["festival", "performance", "cassette"], "כוכבת ילדים.", "Ochi", { tags: ["ילדים"] }),
  p("dan-shatzberg-w2", "דן שצברג", ["dubbing", "film", "series"], "מדבב ישראלי באנימציה."),
  p("gilad-kelter-w2", "גלעד קלטר", ["dubbing", "film", "series"], "מדבב ישראלי.", "Gilad Kalter"),
  p("einat-gliksman-w2", "עינת גליקסמן", ["dubbing", "series", "film"], "מדבבת ישראלית.", "Einat Gliksman"),
  p("hadar-shahaf-w2", "הדר שחף־מעיין", ["dubbing", "film", "series"], "מדבבת ישראלית.", "Hadar Shahaf-Maayan"),
  p("eran-mor-w2", "ערן מור", ["dubbing", "film", "series"], "מדבב — דמויות פיקסאר/דיסני.", "Eran Mor"),
  p("simcha-barbiro-w2", "שמחה ברבירו", ["dubbing", "series", "film", "cassette"], "מדבב קומי מוכר.", "Simcha Barbiro"),
  p("efi-ben-israel-w2", "אפי בן ישראל", ["dubbing", "musical", "series", "film", "performance"], "מדבבת, זמרת ושחקנית.", "Efi Ben Israel"),
  p("miki-kam-w2", "מיקי קם", ["dubbing", "stage", "film", "series", "performance"], "שחקנית, קומיקאית ומדבבת.", "Miki Kam"),
  p("dudu-zar-w2", "דודו זר", ["dubbing", "musical", "festival", "performance", "series"], "שחקן, זמר ומדבב.", "Dudu Zar"),
  p("tal-mosseri-w2", "טל מוסרי", ["hosting", "dubbing", "festival", "series", "performance"], "שחקן, מנחה ומדבב.", "Tal Mosseri"),
  p("tomer-sharon-w2", "תומר שרון", ["dubbing", "film", "series", "stage", "performance"], "שחקן, קומיקאי ומדבב (טרייסי).", "Tomer Sharon", { nicknames: ["טרייסי"] }),
  p("ami-mandelman-w2", "עמי מנדלמן", ["dubbing", "musical", "film", "series", "performance"], "מדבב וזמר מרכזי.", "Ami Mandelman"),
  p("shafrira-zachai-w2", "שפרירה זכאי", ["dubbing", "film", "series", "cassette", "stage"], "חלוצת הדיבוב העברי.", "Shafrira Zachai", { birthDate: "1932-01-01", tags: ["דיבוב", "חלוצה"] }),
  p("yaffa-gabay-w2", "יפה גבאי", ["dubbing", "series", "cassette", "film"], "מוותיקות הדיבוב בישראל.", "Yaffa Gabay"),
  p("rama-messinger-w2", "רמה מסינגר", ["dubbing", "musical", "stage", "film", "series", "performance"], "שחקנית, זמרת ומדבבת.", "Rama Messinger", { deathDate: "2015-07-18", tags: ["מחזמר", "דיבוב"] }),
  p("yoram-yosefsberg-w2", "יורם יוספסברג", ["dubbing", "series", "film", "cassette"], "מדבב ותיק.", "Yoram Yosefsberg"),
  p("avi-hadash-w2", "אבי חדש", ["dubbing", "series", "film"], "מדבב ושחקן.", "Avi Hadash"),
  p("tsvika-furman-w2", "צביקה פורמן", ["dubbing", "series", "film", "cassette"], "מדבב ישראלי.", "Tsvika Furman"),
  p("shiri-gadni-w2", "שירי גדני", ["dubbing", "film", "series", "stage"], "שחקנית ומדבבת.", "Shiri Gadni"),
  p("laura-shopov-w2", "לורה שופוב", ["dubbing", "film", "series"], "מדבבת ישראלית.", "Laura Shopov"),
  p("eliana-magon-w2", "אליענה מגון", ["dubbing", "series", "film"], "מדבבת ושחקנית.", "Eliana Magon"),
  p("maya-dagan-w2", "מיה דגן", ["series", "dubbing", "film"], "שחקנית ומדבבת.", "Maya Dagan", { birthDate: "1971-05-01" }),
  p("moni-moshonov-w2", "מוני מושונוב", ["stage", "film", "series", "performance"], "שחקן וקומיקאי.", "Moni Moshonov"),
  p("shlomo-baraba-w2", "שלמה בראבא", ["stage", "film", "series", "performance"], "שחקן וקומיקאי.", "Shlomo Baraba"),
  p("shasi-keshet-w2", "ששי קשת", ["musical", "stage", "performance", "film"], "זמר וכוכב מחזמרים.", "Sassi Keshet"),
  p("riki-gal-w2", "ריקי גל", ["musical", "performance", "stage", "film"], "זמרת ושחקנית.", "Riki Gal"),
  p("eli-gorenstein-w2", "אלי גורנשטיין", ["dubbing", "film", "series", "stage", "musical"], "שחקן, זמר ומדבב.", "Eli Gorenstein"),
  p("dov-reiber-w2", "דב רייזר", ["dubbing", "film", "series", "stage"], "שחקן ומדבב ותיק.", "Dov Reiser"),
  p("yehezkel-lazarov-w2", "יחזקאל לזרוב", ["film", "series", "stage", "dubbing", "musical"], "שחקן ורקדן.", "Yehezkel Lazarov"),
  p("ania-bukstein-w2", "אניה בוקשטיין", ["film", "series", "stage", "dubbing"], "שחקנית ישראלית.", "Ania Bukstein"),
  p("liraz-charhi-w2", "לירז צ׳רכי", ["film", "series", "stage", "musical", "performance"], "שחקנית וזמרת.", "Liraz Charhi"),
  p("israel-katorza-w2", "ישראל קטורזה", ["series", "stage", "performance", "film"], "קומיקאי ושחקן.", "Israel Katorza"),
  p("shalom-asayag", "שלום אסייג", ["series", "stage", "performance", "film"], "קומיקאי ושחקן.", "Shalom Asayag"),
  p("eli-finish-w2", "אלי פיניש", ["series", "stage", "performance", "film"], "קומיקאי ושחקן.", "Eli Finish"),
  p("natalie-atiya-w2", "נטעלי עטייה", ["festival", "performance", "series", "musical"], "שחקנית וכוכבת פסטיגל.", "Netta Garti"),
  p("eden-hason-w2", "עדן חסון", ["musical", "performance", "festival"], "זמר ישראלי.", "Eden Hason"),
  p("static-w2", "סטטיק", ["performance", "festival", "musical"], "אמן במה.", "Static (rapper)"),
  p("ben-el-w2", "בן אל תבורי", ["performance", "festival", "musical"], "זמר ואמן במה.", "Ben El Tavori"),
  p("ido-rosenblum-w2", "עידו רוזנבלום", ["hosting", "series", "performance", "festival"], "מנחה ושחקן.", "Ido Rosenblum"),
  p("sapir-dermon-w2", "ספיר דרמון", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("yoav-tsarfati-w2", "יואב צרפתי", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("mati-atlas-w2", "מתי אטלס", ["dubbing", "series", "cassette", "film"], "מדבב ותיק."),
  p("gilit-shoval-w2", "גיתית שובל", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("assaf-preenta-w2", "אסף פריינטא", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("michal-reshef-w2", "מיכל רשף", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("debi-beserglik-w2", "דבי בסרגליק", ["dubbing", "cassette", "series", "film"], "מדבבת ותיקה.", "Debi Beserglik"),
  p("orna-katz-w2", "אורנה כץ", ["dubbing", "series", "cassette", "film"], "מדבבת ישראלית."),
  p("alon-neumann-w2", "אלון נוימן", ["dubbing", "film", "series", "stage"], "שחקן ומדבב."),
  p("nir-ron-w2", "ניר רון", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("tamir-ginsburg-w2", "תמיר גינזבורג", ["dubbing", "film", "series"], "שחקן ומדבב.", "Tamir Ginsburg"),
  p("dani-bassan-w2", "דני בסן", ["musical", "performance", "stage"], "זמר ושחקן מחזמר.", "Dani Bassan"),
  p("ayelet-robinson-w2", "איילת רובינסון", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  // שחקני ילדים/נוער עכשוויים יותר
  p("liam-giini-w2", "ליאם ג׳יני", ["festival", "series", "performance"], "שחקן ילדים/נוער.", undefined, { tags: ["ילדים", "נוער"] }),
  p("noam-ben-gur-w2", "נועם בן גור", ["festival", "series", "performance", "dubbing"], "שחקן ילדים/נוער ומדבב.", undefined, { tags: ["ילדים"] }),
  p("ofek-pati-w2", "אופק פטי", ["festival", "series", "performance", "dubbing"], "שחקן ילדים/נוער.", undefined, { tags: ["ילדים"] }),
  p("halleli-avi-w2", "הללי אבי", ["festival", "series", "performance"], "שחקנית ילדים/נוער.", undefined, { tags: ["ילדים"] }),
  p("romi-parkh-w2", "רומי פרחומובסקי", ["series", "festival", "performance", "dubbing"], "שחקנית ילדים/נוער."),
  p("yahel-sherman-w2", "יהל שרמן", ["dubbing", "series", "film"], "מדבב/ת בהפקות ילדים."),
  p("chen-cohen-w2", "חן כהן", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("itay-shinman-w2", "איתי שינמן", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("sivan-sharon-w2", "סיון שרון", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("yoav-hayun-w2", "יואב חיון", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("talya-cohen-w2", "טליה כהן", ["dubbing", "series", "film"], "מדבבת בהפקות ילדים ונוער."),
  p("jonathan-ptishi-w2", "יונתן פטישי", ["dubbing", "film", "series"], "מדבב באנימציה."),
  p("ortal-zamir-w2", "אורטל זמיר", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("adi-kozlovsky-w2", "עדי קוזלובסקי", ["dubbing", "series", "film"], "מדבבת ילדים ונוער."),
  p("noa-kashpitzky-w2", "נועה קשפיצקי", ["dubbing", "series", "film"], "מדבבת ישראלית."),
  p("barak-brinksman-w2", "ברק בריקמן", ["dubbing", "film", "series"], "מדבב באנימציה."),
  p("alon-sharr-w2", "אלון שר", ["dubbing", "film", "series"], "מדבב ישראלי."),
  p("yangal-glazer-w2", "ינגל גלזר־ז׳אן", ["dubbing", "series", "film"], "מדבבת ישראלית.", "Inbal Glazer"),
  p("yuval-segal-w2", "יובל סגל", ["dubbing", "film", "series", "stage"], "שחקן ומדבב.", "Yuval Segal"),
  p("michael-moshonov-w2", "מיכאל מושונוב", ["film", "series", "stage", "dubbing"], "שחקן ישראלי.", "Michael Moshonov"),
];

export const WAVE2_PRODUCTIONS: Production[] = [
  prod("frozen-he", "לשבור את הקרח", 2013, "film", "דיבוב עברי לסרט דיסני — שירה, דמויות ומחזמר־אנימציה.", ["אנימציה", "דיסני", "מחזמר"], { originalTitle: "Frozen" }),
  prod("frozen2-he", "לשבור את הקרח 2", 2019, "film", "המשך דיבוב דיסני בעברית.", ["אנימציה", "דיסני"], { originalTitle: "Frozen II" }),
  prod("moana-he", "מואנה", 2016, "film", "סרט דיסני מדובב עם דגש על שירה.", ["אנימציה", "דיסני", "מחזמר"], { originalTitle: "Moana" }),
  prod("encanto-he", "אנקאנטו", 2021, "film", "דיבוב עברי לסרט דיסני.", ["אנימציה", "דיסני"], { originalTitle: "Encanto" }),
  prod("coco-he", "קוקו", 2017, "film", "דיבוב פיקסאר/דיסני לעברית.", ["אנימציה", "פיקסאר"], { originalTitle: "Coco" }),
  prod("inside-out-he", "הקול בראש", 2015, "film", "דיבוב פיקסאר לעברית.", ["אנימציה", "פיקסאר"], { originalTitle: "Inside Out" }),
  prod("toy-story-he", "צעצוע של סיפור", 1995, "film", "קלאסיקת דיבוב פיקסאר בעברית.", ["אנימציה", "פיקסאר"], { originalTitle: "Toy Story" }),
  prod("toy-story-4-he", "צעצוע של סיפור 4", 2019, "film", "המשך דיבוב פיקסאר.", ["אנימציה", "פיקסאר"], { originalTitle: "Toy Story 4" }),
  prod("finding-nemo-he", "מוצאים את נמו", 2003, "film", "דיבוב פיקסאר קלאסי.", ["אנימציה", "פיקסאר"], { originalTitle: "Finding Nemo" }),
  prod("shrek-he", "שרק", 2001, "film", "דיבוב עברי לקומדיית אנימציה.", ["אנימציה", "קומדיה"], { originalTitle: "Shrek" }),
  prod("shrek-2-he", "שרק 2", 2004, "film", "המשך דיבוב שרק.", ["אנימציה"], { originalTitle: "Shrek 2" }),
  prod("despicable-me-he", "גנוב על הירח", 2010, "film", "דיבוב עברי להפקת אילומיניישן.", ["אנימציה"], { originalTitle: "Despicable Me" }),
  prod("minions-he", "מיניונים", 2015, "film", "דיבוב עברי.", ["אנימציה"], { originalTitle: "Minions" }),
  prod("zootopia-he", "זוטרופוליס", 2016, "film", "דיבוב דיסני לעברית.", ["אנימציה", "דיסני"], { originalTitle: "Zootopia" }),
  prod("big-hero-6-he", "שישה גיבורים", 2014, "film", "דיבוב דיסני/מארוול אנימציה.", ["אנימציה", "דיסני"], { originalTitle: "Big Hero 6" }),
  prod("tangled-he", "פלונטר", 2010, "film", "דיבוב דיסני — נסיכה, שירה וקומדיה.", ["אנימציה", "דיסני", "מחזמר"], { originalTitle: "Tangled" }),
  prod("mulan-he", "מולאן", 1998, "film", "דיבוב דיסני קלאסי.", ["אנימציה", "דיסני"], { originalTitle: "Mulan" }),
  prod("beauty-beast-he", "היפה והחיה", 1991, "film", "דיבוב דיסני עם שירים אייקוניים.", ["אנימציה", "דיסני", "מחזמר"], { originalTitle: "Beauty and the Beast" }),
  prod("snow-white-he", "שלגיה ושבעת הגמדים", 1937, "film", "דיבוב עברי לקלאסיקת דיסני (גרסאות שונות).", ["אנימציה", "דיסני"], { originalTitle: "Snow White" }),
  prod("pocahontas-he", "פוקהונטס", 1995, "film", "דיבוב דיסני.", ["אנימציה", "דיסני"], { originalTitle: "Pocahontas" }),
  prod("hercules-he", "הרקולס", 1997, "film", "דיבוב דיסני עם דגש קומי ושירי מחזמר.", ["אנימציה", "דיסני", "מחזמר"], { originalTitle: "Hercules" }),
  prod("tarzan-he", "טרזן", 1999, "film", "דיבוב דיסני.", ["אנימציה", "דיסני"], { originalTitle: "Tarzan" }),
  prod("nemo-dory-he", "מוצאים את דורי", 2016, "film", "המשך דיבוב פיקסאר.", ["אנימציה", "פיקסאר"], { originalTitle: "Finding Dory" }),
  prod("incredibles-he", "משפחת סופר־על", 2004, "film", "דיבוב פיקסאר.", ["אנימציה", "פיקסאר"], { originalTitle: "The Incredibles" }),
  prod("up-he", "למעלה", 2009, "film", "דיבוב פיקסאר.", ["אנימציה", "פיקסאר"], { originalTitle: "Up" }),
  prod("spiderverse-he", "ספיידרמן: מימד העכביש", 2018, "film", "דיבוב עברי לאנימציית סופר־גיבורים.", ["אנימציה", "מארוול"], { originalTitle: "Spider-Man: Into the Spider-Verse" }),
  prod("super-mario-he", "האחים סופר מריו", 2023, "film", "דיבוב עברי לסרט אנימציה.", ["אנימציה"], { originalTitle: "The Super Mario Bros. Movie" }),
  prod("wish-he", "משאלה", 2023, "film", "דיבוב דיסני עכשווי.", ["אנימציה", "דיסני"], { originalTitle: "Wish" }),
  prod("elemental-he", "יסודות", 2023, "film", "דיבוב פיקסאר.", ["אנימציה", "פיקסאר"], { originalTitle: "Elemental" }),
  prod("paw-patrol-he", "מפרץ ההרפתקאות", 2013, "series", "סדרת ילדים מדובבת פופולרית.", ["ילדים", "אנימציה"], { originalTitle: "PAW Patrol", channel: "ניק ג׳וניור" }),
  prod("peppa-pig-he", "פפה פיג", 2004, "series", "סדרת ילדים מדובבת.", ["ילדים", "אנימציה"], { originalTitle: "Peppa Pig" }),
  prod("spongebob-he", "בובספוג", 1999, "series", "סדרה מדובבת אייקונית.", ["ילדים", "קומדיה"], { originalTitle: "SpongeBob SquarePants", channel: "ניקלודיאון" }),
  prod("pokemon-he", "פוקימון", 1997, "series", "אנימה מדובבת לעברית.", ["אנימה", "ילדים"], { originalTitle: "Pokémon", channel: "ערוץ הילדים" }),
  prod("naruto-he", "נארוטו", 2002, "series", "אנימה מדובבת (חלקים/שידורים בישראל).", ["אנימה"], { originalTitle: "Naruto" }),
  prod("dragonball-he", "דרגון בול", 1986, "series", "אנימה מדובבת קלאסית בישראל.", ["אנימה"], { originalTitle: "Dragon Ball" }),
  prod("sailormoon-he", "סיילור מון", 1992, "series", "אנימה מדובבת ששודרה בישראל.", ["אנימה", "ילדים"], { originalTitle: "Sailor Moon" }),
  prod("totally-spies-he", "שלוש אספנות", 2001, "series", "סדרת ילדים/נוער מדובבת.", ["ילדים", "אנימציה"], { originalTitle: "Totally Spies!" }),
  prod("winx-he", "מועדון ווינקס", 2004, "series", "סדרה מדובבת לילדים.", ["ילדים", "אנימציה"], { originalTitle: "Winx Club" }),
  prod("miraculous-he", "המשושים", 2015, "series", "סדרת ילדים מדובבת.", ["ילדים", "אנימציה"], { originalTitle: "Miraculous" }),
  prod("bluey-he", "בלואי", 2018, "series", "סדרת ילדים מדובבת.", ["ילדים"], { originalTitle: "Bluey" }),
  prod("sesame-israel", "רחוב סומסום", 1983, "series", "הפקה ישראלית־בינלאומית לילדים.", ["ילדים", "חינוכי"], { originalTitle: "Sesame Street", channel: "הטלוויזיה החינוכית" }),
  prod(
    "parpar-nechmad",
    "פרפר נחמד (העונות הראשונות)",
    1982,
    "series",
    "סדרת ילדים ישראלית קלאסית של הטלוויזיה החינוכית — העונות הראשונות. ערך מקביל לארכיון ערוץ הופ תמיר (1982–1997).",
    ["ילדים", "ישראלי", "חינוכי", "בובות"],
    { channel: "הטלוויזיה החינוכית", endYear: 1997 }
  ),
  prod("hop", "הופ!", 2007, "series", "ערוץ/מותג ילדים ישראלי והפקות נלוות.", ["ילדים"], { channel: "הופ!" }),
  prod("festigal-2020s", "הפסטיגל (שנות ה־2000–2020)", 2000, "festival", "מופעי פסטיגל לאורך השנים — שחקנים, זמרים וכוכבי ילדים.", ["ילדים", "מופע", "שירה"]),
  prod("festigal-classic", "הפסטיגל הקלאסי", 1981, "festival", "מופע הילדים הישראלי השנתי.", ["ילדים", "מופע"]),
  prod("mamma-mia-il", "מאמה מיה! (מחזמר בישראל)", 2000, "musical", "מחזמר בינלאומי שהועלה בישראל.", ["מחזמר", "במה"], { originalTitle: "Mamma Mia!" }),
  prod("hamilton-il", "המילטון (הפקה ישראלית/בינלאומית)", 2020, "musical", "מחזמר עכשווי בהקשר ישראלי/בינלאומי.", ["מחזמר"], { originalTitle: "Hamilton" }),
  prod("phantom-il", "פנטום האופרה (מחזמר בישראל)", 1995, "musical", "מחזמר קלאסי שהועלה בישראל.", ["מחזמר", "במה"], { originalTitle: "The Phantom of the Opera" }),
  prod("chicago-il", "שיקגו (מחזמר בישראל)", 2000, "musical", "מחזמר בינלאומי בגרסה ישראלית.", ["מחזמר"], { originalTitle: "Chicago" }),
  prod("wicked-il", "ויקד (מחזמר)", 2010, "musical", "מחזמר בינלאומי שהופיע גם בהקשר ישראלי.", ["מחזמר"], { originalTitle: "Wicked" }),
  prod("katzav-shel-anashim", "קצב של אנשים / מופעי ילדים", 1990, "performance", "מופעי במה וילדים ישראליים.", ["ילדים", "הופעה"]),
  prod("disney-on-ice-il", "דיסני על הקרח בישראל", 2005, "performance", "מופע משפחתי עם דמויות דיסני.", ["ילדים", "הופעה"]),
  prod("cassette-chani", "קלטות ילדים ישראליות קלאסיות", 1985, "cassette", "ארכיון מייצג של קלטות שמע/וידאו לילדים.", ["קלטות", "ילדים"]),
  prod("ha-ilemet", "היפהפייה והיחפן / דיבובים קלאסיים", 1980, "film", "דיבובים קלאסיים לילדים בישראל.", ["אנימציה", "ילדים"]),
  prod("the-lion-king-musical-il", "מלך האריות (מחזמר בישראל)", 2004, "musical", "מחזמר מלך האריות בגרסאות בינלאומיות/ישראליות.", ["מחזמר", "במה"], { originalTitle: "The Lion King Musical" }),
  prod("aladdin-musical-il", "אלאדין (מחזמר)", 2015, "musical", "מחזמר דיסני.", ["מחזמר"], { originalTitle: "Aladdin Musical" }),
  prod("grease-il", "גריז (מחזמר בישראל)", 1990, "musical", "מחזמר קלאסי שהועלה בישראל.", ["מחזמר"], { originalTitle: "Grease" }),
  prod("joseph-il", "יוסף והפנטזיה המדהימה (מחזמר)", 1990, "musical", "מחזמר שהועלה בישראל.", ["מחזמר"], { originalTitle: "Joseph and the Amazing Technicolor Dreamcoat" }),
  prod("ha-hamama-musical-ish", "החממה — מופעים והפקות נלוות", 2013, "performance", "מופעים והופעות סביב סדרת החממה.", ["נוער", "הופעה"]),
  prod("north-star-kids", "כוכבי ילדים — מופעי ענק", 2010, "festival", "מופעי ילדים ישראליים עם שחקנים וזמרים.", ["ילדים", "מופע"]),
  prod(
    "kofiko",
    "קופיקו",
    1993,
    "series",
    "סדרת טלוויזיה ישראלית לילדים המבוססת על ספרי תמר בורנשטיין-לזר. עונה 1 ב־1993; עונות 2–4 (2009–2013) בערוץ ג'וניור / yes.",
    ["ילדים", "ישראלי", "קומדיה", "בובות"],
    {
      channel: "ערוץ הילדים / ג'וניור",
      endYear: 2013,
      imageUrl: portrait("קופיקו"),
    }
  ),
  prod(
    "kofiko-jungle-laws",
    "קופיקו – חוקי הג'ונגל",
    2010,
    "series",
    "ספין־אוף קצר של «קופיקו» (עונה 2) — קופיקו כשופט בסדרת רשת. שודרה בערוץ ג'וניור / yes / וואלה.",
    ["ילדים", "ישראלי", "קומדיה", "בובות"],
    { channel: "ערוץ ג'וניור", imageUrl: portrait("קופיקו – חוקי הג'ונגל") }
  ),
];

function c(personId: string, productionId: string, role: Credit["role"], characterName?: string): Credit {
  return { personId, productionId, role, characterName };
}

/** קישוריות רחבה: כל מדבב/מופיע מחובר להפקות רלוונטיות */
export const WAVE2_CREDITS: Credit[] = [
  c("sharon-cohen", "frozen-he", "dub_director"),
  c("sharon-cohen", "moana-he", "dub_director"),
  c("sharon-cohen", "zootopia-he", "dub_director"),
  c("sharon-cohen", "tangled-he", "dubber"),
  c("ami-mandelman-w2", "frozen-he", "dubber"),
  c("ami-mandelman-w2", "shrek-he", "dubber"),
  c("ami-mandelman-w2", "hercules-he", "dubber"),
  c("liron-lev", "frozen-he", "singer"),
  c("liron-lev", "moana-he", "dubber"),
  c("liron-lev", "beauty-beast-he", "singer"),
  c("eran-mor-w2", "toy-story-4-he", "dubber"),
  c("eran-mor-w2", "inside-out-he", "dubber"),
  c("eran-mor-w2", "coco-he", "dubber"),
  c("kobi-likverman", "big-hero-6-he", "dubber"),
  c("kobi-likverman", "spiderverse-he", "dubber"),
  c("kobi-likverman", "super-mario-he", "dubber"),
  c("daniel-magon", "toy-story-he", "dubber"),
  c("daniel-magon", "finding-nemo-he", "dubber"),
  c("daniel-magon", "festigal-classic", "musical_performer"),
  c("yonatan-magon", "pokemon-he", "dubber"),
  c("eliana-magon-w2", "totally-spies-he", "dubber"),
  c("laura-shopov-w2", "tangled-he", "dubber"),
  c("laura-shopov-w2", "frozen-he", "dubber"),
  c("hadar-shahaf-w2", "frozen-he", "dubber"),
  c("hadar-shahaf-w2", "moana-he", "dubber"),
  c("hadar-shahaf-w2", "encanto-he", "dubber"),
  c("einat-gliksman-w2", "paw-patrol-he", "dubber"),
  c("einat-gliksman-w2", "peppa-pig-he", "dubber"),
  c("tsvika-furman-w2", "spongebob-he", "dubber"),
  c("tsvika-furman-w2", "dragonball-he", "dubber"),
  c("simcha-barbiro-w2", "shrek-he", "dubber"),
  c("simcha-barbiro-w2", "hercules-he", "dubber"),
  c("yoram-yosefsberg-w2", "sesame-israel", "dubber"),
  c("yoram-yosefsberg-w2", "parpar-nechmad", "actor"),
  c("tuvia-tsafir", "sesame-israel", "actor"),
  c("tuvia-tsafir", "shrek-he", "dubber"),
  c("tuvia-tsafir", "cassette-chani", "dubber"),
  c("shafrira-zachai-w2", "snow-white-he", "dub_director"),
  c("shafrira-zachai-w2", "beauty-beast-he", "dub_director"),
  c("yaffa-gabay-w2", "parpar-nechmad", "dubber"),
  c("yaffa-gabay-w2", "cassette-chani", "dubber"),
  c("rama-messinger-w2", "beauty-beast-he", "dubber"),
  c("rama-messinger-w2", "the-lion-king-musical-il", "musical_performer"),
  c("rama-messinger-w2", "mamma-mia-il", "musical_performer"),
  c("efi-ben-israel-w2", "mulan-he", "dubber"),
  c("efi-ben-israel-w2", "pocahontas-he", "singer"),
  c("miki-kam-w2", "festigal-2020s", "musical_performer"),
  c("dudu-zar-w2", "festigal-2020s", "singer"),
  c("dudu-zar-w2", "cassette-chani", "singer"),
  c("tal-mosseri-w2", "festigal-2020s", "host"),
  c("tal-mosseri-w2", "hop", "host"),
  c("ido-mosseri-w2", "festigal-2020s", "musical_performer"),
  c("tomer-sharon-w2", "festigal-classic", "musical_performer"),
  c("zipi-shavit", "cassette-chani", "singer"),
  c("zipi-shavit", "festigal-classic", "singer"),
  c("zipi-shavit", "north-star-kids", "singer"),
  c("yuval-hamvulbal-w2", "festigal-2020s", "host"),
  c("yuval-hamvulbal-w2", "hop", "actor"),
  c("yuval-hamvulbal-w2", "cassette-chani", "singer"),
  c("michal-haqtana", "festigal-classic", "singer"),
  c("mariko-w2", "cassette-chani", "singer"),
  c("uchi-w2", "cassette-chani", "singer"),
  c("shasi-keshet-w2", "phantom-il", "musical_performer"),
  c("shasi-keshet-w2", "chicago-il", "musical_performer"),
  c("riki-gal-w2", "mamma-mia-il", "singer"),
  c("riki-gal-w2", "grease-il", "musical_performer"),
  c("rita-w2", "chicago-il", "singer"),
  c("ninet-tayeb-w2", "chicago-il", "musical_performer"),
  c("harel-skaat-w2", "the-lion-king-musical-il", "singer"),
  c("harel-skaat-w2", "joseph-il", "musical_performer"),
  c("shiri-mimon-w2", "mamma-mia-il", "musical_performer"),
  c("shiri-mimon-w2", "wicked-il", "singer"),
  c("amit-farkash-w2", "grease-il", "musical_performer"),
  c("amit-farkash-w2", "ha-hamama-musical-ish", "singer"),
  c("gidi-gov-w2", "joseph-il", "singer"),
  c("yardena-arazi-w2", "festigal-classic", "host"),
  c("svika-pick-w2", "festigal-classic", "composer"),
  c("noa-kirel-w2", "festigal-2020s", "singer"),
  c("noa-kirel-w2", "north-star-kids", "singer"),
  c("anna-zak-w2", "festigal-2020s", "singer"),
  c("eden-hason-w2", "north-star-kids", "singer"),
  c("static-w2", "north-star-kids", "singer"),
  c("ben-el-w2", "north-star-kids", "singer"),
  c("dani-bassan-w2", "grease-il", "musical_performer"),
  c("eli-gorenstein-w2", "beauty-beast-he", "dubber"),
  c("eli-gorenstein-w2", "phantom-il", "musical_performer"),
  c("gilad-kelter-w2", "zootopia-he", "dubber"),
  c("gilad-kelter-w2", "incredibles-he", "dubber"),
  c("avi-hadash-w2", "hercules-he", "dubber"),
  c("avi-hadash-w2", "shrek-2-he", "dubber"),
  c("debi-beserglik-w2", "cassette-chani", "dubber"),
  c("orna-katz-w2", "sailormoon-he", "dubber"),
  c("sapir-dermon-w2", "miraculous-he", "dubber"),
  c("sapir-dermon-w2", "winx-he", "dubber"),
  c("maya-dagan-w2", "ha-hamama-musical-ish", "actor"),
  c("yon-tumarkin-w2", "ha-hamama-musical-ish", "actor"),
  c("adi-himelbloy-w2", "ha-hamama-musical-ish", "actor"),
  c("agam-rodberg", "festigal-2020s", "musical_performer"),
  c("liam-giini-w2", "festigal-2020s", "musical_performer"),
  c("noam-ben-gur-w2", "festigal-2020s", "musical_performer"),
  c("ofek-pati-w2", "paw-patrol-he", "dubber"),
  c("halleli-avi-w2", "festigal-2020s", "musical_performer"),
  c("romi-parkh-w2", "miraculous-he", "dubber"),
  c("ido-rosenblum-w2", "festigal-2020s", "host"),
  c("natalie-atiya-w2", "festigal-2020s", "musical_performer"),
  c("tamir-ginsburg-w2", "spiderverse-he", "dubber"),
  c("dan-shatzberg-w2", "despicable-me-he", "dubber"),
  c("alon-neumann-w2", "up-he", "dubber"),
  c("nir-ron-w2", "minions-he", "dubber"),
  c("yoav-tsarfati-w2", "elemental-he", "dubber"),
  c("mati-atlas-w2", "cassette-chani", "dubber"),
  c("shiri-gadni-w2", "frozen2-he", "dubber"),
  c("ayelet-robinson-w2", "bluey-he", "dubber"),
  c("gilit-shoval-w2", "peppa-pig-he", "dubber"),
  c("assaf-preenta-w2", "wish-he", "dubber"),
  c("michal-reshef-w2", "encanto-he", "dubber"),
  c("barak-brinksman-w2", "super-mario-he", "dubber"),
  c("alon-sharr-w2", "spiderverse-he", "dubber"),
  c("yuval-segal-w2", "incredibles-he", "dubber"),
  c("michael-moshonov-w2", "disney-on-ice-il", "actor"),
  c("moni-moshonov-w2", "mamma-mia-il", "actor"),
  c("shlomo-baraba-w2", "grease-il", "actor"),
  c("yehezkel-lazarov-w2", "chicago-il", "musical_performer"),
  c("ania-bukstein-w2", "frozen-he", "dubber"),
  c("liraz-charhi-w2", "mamma-mia-il", "singer"),
  c("dov-reiber-w2", "beauty-beast-he", "dubber"),
  c("lihi-kornowski", "festigal-2020s", "actor"),
  c("daniel-gad", "ha-hamama-musical-ish", "actor"),
  c("michael-alinor", "chicago-il", "actor"),
  c("rotum-sela", "festigal-2020s", "host"),
];
