import type { Credit, Person, Production } from "./types";
import { portrait } from "./portrait";

/** Seed batch from https://sites.google.com/view/hoptamir (ערוץ הופ תמיר) */
const now = "2026-07-24T12:00:00.000Z";

function p(
  id: string,
  name: string,
  bio: string,
  also?: string,
  nicknames: string[] = []
): Person {
  return {
    id,
    name,
    nicknames,
    tags: ["דיבוב", "הופ תמיר"],
    activities: ["dubbing", "series", "film"],
    bio,
    nameOriginal: also,
    imageUrl: portrait(name, also),
    createdAt: now,
    updatedAt: now,
  };
}

function prod(
  id: string,
  title: string,
  year: number,
  summary: string,
  extra: Partial<Production> = {}
): Production {
  return {
    id,
    title,
    year,
    kind: extra.kind || "series",
    summary,
    genres: extra.genres || ["אנימציה", "ילדים", "דיבוב"],
    originalTitle: extra.originalTitle,
    endYear: extra.endYear,
    channel: extra.channel || "הופ תמיר",
    studio: extra.studio,
    dubbingStudio: extra.dubbingStudio,
    imageUrl: extra.imageUrl || portrait(title),
    createdAt: now,
    updatedAt: now,
  };
}

export const HOP_TAMIR_PEOPLE: Person[] = [
  p("ht-chnh-drvry-kshy", "חנה דרורי קשי", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Hanna Drori Kashi"),
  p("ht-chsyh-vrthyym", "חסיה ורטהיים", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Hasia Wertheim"),
  p("ht-rvty-hvltzmn", "רותי הולצמן", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Ruti Holtzman"),
  p("ht-avrnh-lbya-plynt", "אורנה לביא פלינט", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Orna Lavi Flint"),
  p("ht-chny-nchmyas", "חני נחמיאס", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Hani Nahmias"),
  p("ht-knrt-trypvn-rshp", "כנרת טריפון רשף", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Kinneret Trifon Reshef"),
  p("ht-pzyt-nvny", "פזית נוני", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר."),
  p("ht-tmy-ashl", "תמי אשל", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר."),
  p("ht-nvryt-bnay-kvrn", "נורית בנאי קורן", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Nurit Banai Koren"),
  p("ht-lylyan-brtv", "ליליאן ברטו", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Lilian Barreto"),
  p("ht-apy-bn-yshral", "אפי בן ישראל", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Efi Ben Israel"),
  p("ht-shmavn-khn", "שמעון כהן", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Shimon Cohen"),
  p("ht-aly-gvrnshtyyn", "אלי גורנשטיין", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Eli Gorenstein"),
  p("ht-avdd-mnshh", "עודד מנשה", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Oded Menashe"),
  p("ht-shchr-tzrpty", "שחר צרפתי", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר."),
  p("ht-shmvlyk-yprch", "שמוליק יפרח", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Shmulik Yifrah"),
  p("ht-yvrm-gl", "יורם גל", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר."),
  p("ht-rvny-vyys", "רוני וייס", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר."),
  p("ht-lah-navr", "לאה נאור", "מדבב/ת ועורך/ת מדיה — ערך מתוך ארכיון ערוץ הופ תמיר.", "Leah Naor"),
  // Cast for המומינים (אנימה) — missing from other seeds; from ויקיפדיה העברית.
  p("ht-yrvn-dgn", "ירון דגן", "מדבב ישראלי — דיבוב מומינטרול בסדרת «המומינים».", "Yaron Dagan"),
  p("ht-asf-khvly", "אסף כחולי", "מדבב ישראלי — דיבוב סניף וסנורק בסדרת «המומינים».", "Asaf Kachuli"),
  p("ht-ayrys-zyngr", "איריס זינגר", "מדבבת ישראלית — דיבוב סנורקה בסדרת «המומינים».", "Iris Zinger"),
  // קופידו — מדבבים חסרים (ויקיפדיה / אישים)
  p("rvnn-gvldprb", "רונן גולדפרב", "שחקן ומדבב ישראלי — בין היתר דיבוב ב«קופידו» (מר צהוב).", "Ronen Goldfarb"),
  p("ahrvn-kpln", "אהרון קפלן", "מדבב ישראלי — השתתף בדיבוב העברי של «קופידו».", "Aharon Kaplan"),
  p("avryt-amyr", "אורית אמיר", "מדבבת ישראלית (נולדה כאורית פרוכטר) — השתתפה בדיבוב «קופידו».", "Orit Amir", ["אורית פרוכטר"]),
  p("shy-kvkvy", "שי קוקוי", "מדבב ישראלי — השתתף בדיבוב העברי של «קופידו».", "Shai Kukoi"),
  // חבובוטף (2018) — מדבבים חסרים (ויקיפדיה)
  p("tzili-yenko", "צילי ינקו", "מדבבת ישראלית — דיבוב מיס פיגי ב«חבובוטף» (2018).", "Tzili Yenko"),
  p("yuval-garbash", "יובל גרבש", "מדבב ישראלי — דיבוב פוזי ב«חבובוטף» (2018).", "Yuval Garbash"),
  p("mona-mor", "מונה מור", "מדבבת ישראלית — דיבוב נני ב«חבובוטף» (2018).", "Mona Mor"),
  p("alona-alexander", "אלונה אלכסנדר", "מדבבת וזמרת ישראלית — דיבוב סאמר ב«חבובוטף» (2018).", "Alona Alexander"),
  p("gadi-levi", "גדי לוי", "מדבב ישראלי — דיבוב וולדורף ב«חבובוטף» (2018).", "Gadi Levi"),
  // נחשון / קופיקו בספרייה
  p("sharon-bar-ezer", "שרון בר עזר", "מדבבת ישראלית — דיבוב חבובה ב«נחשון כל יכול».", "Sharon Bar Ezer"),
  p("hila-shlagel", "הילה שלגל", "שחקנית ומדבבת — גילמה את מיפו ב«קופיקו בספרייה».", "Hila Shlagel"),
];

export const HOP_TAMIR_PRODUCTIONS: Production[] = [
  // Featured with rich metadata from the site homepage
  prod(
    "ht-peter-pan-adventures",
    "פיטר פן",
    1990,
    "פיטר פן, הילד הנצחי, לוקח את ילדי משפחת דארלינג להרפתקה קסומה בארץ לעולם־לא. סדרת אנימציה יפנית מדובבת (39 פרקים, כ־24 דקות). ערך מתוך ערוץ הופ תמיר.",
    {
      originalTitle: "The Adventures of Peter Pan / ピーターパンの冒険",
      endYear: 1991,
      channel: "חינוכית / הופ תמיר",
      genres: ["אנימציה", "ילדים", "דיבוב", "מדובב - זר"],
      imageUrl: portrait("פיטר פן", "The Adventures of Peter Pan"),
    }
  ),
  // Featured: listed in hoptamir-prods.json as „טימון ופומבה (1997-1999)” (beyond generator MAX=180);
  // cast from Hop Tamir / אישים + ויקיפדיה העברית.
  prod(
    "ht-tymvn-vpvmbh",
    "טימון ופומבה",
    1997,
    "ספין־אוף אנימציה של מלך האריות — הרפתקאות טימון ופומבה. שודרה בזמן דיסני בערוץ 2 בדיבוב שפרירה זכאי; ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      originalTitle: "The Lion King's Timon & Pumbaa",
      endYear: 1999,
      channel: "ערוץ 2 / זמן דיסני",
      studio: "סרטי אז",
      genres: ["אנימציה", "ילדים", "דיבוב", "מדובב - זר", "קומדיה"],
      imageUrl: portrait("טימון ופומבה", "Timon & Pumbaa"),
    }
  ),
  // Featured: listed in hoptamir-prods.json as „היה היה - דואגים לכדור הארץ (2009)” (beyond generator MAX=180);
  // title/cast from ויקיפדיה העברית (שם הפצה בישראל) + ארכיון הופ תמיר.
  prod(
    "ht-hyh-hyh-dvagym-lkdvr-hartz",
    "היה היה - דואגים לכדור הארץ",
    2008,
    "סדרת אנימציה צרפתית חינוכית על אקולוגיה ואיכות הסביבה מבית «היה היה» (פרוסידיס / אלבר בארייה). שודרה בישראל בערוץ לוגי בדיבוב עברי בבימוי אפי בן ישראל; ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      originalTitle: "Il était une fois... notre Terre",
      endYear: 2009,
      channel: "לוגי",
      genres: ["אנימציה", "ילדים", "דיבוב", "מדובב - זר", "חינוכי"],
      imageUrl: portrait(
        "היה היה - דואגים לכדור הארץ",
        "Il était une fois... notre Terre"
      ),
    }
  ),
  // Featured: listed in hoptamir-prods.json as „המומינים” (beyond generator MAX=180);
  // cast from ויקיפדיה העברית (המומינים — אנימה) + ארכיון הופ תמיר.
  prod(
    "ht-hmvmywnym",
    "המומינים",
    1992,
    "סדרת אנימה יפנית־הולנדית המבוססת על ספרי טובה ינסון. שודרה בישראל בטלוויזיה החינוכית / ג׳וניור (1992–2000) מדיבוב באולפני זינקו בבימוי חנה דרורי קשי; ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      originalTitle: "楽しいムーミン一家 / Tanoshii Mūmin Ikka",
      endYear: 2000,
      channel: "חינוכית / ג'וניור",
      dubbingStudio: "אולפני זינקו",
      genres: ["אנימציה", "ילדים", "דיבוב", "מדובב - זר", "אנימה", "פנטזיה"],
      imageUrl: portrait("המומינים", "Moomin"),
    }
  ),
  prod("ht-hkrb-al-hpvp-tart", "הקרב על הפופ-טארט", 2024, "הפקה מארכיון ערוץ הופ תמיר (2024).", { kind: "series" }),
  prod("ht-hyv-hyh-stvdyv", "היו היה סטודיו", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-vyvtypvl-g-v", "ויוטיפול ג'ו", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "series" }),
  prod("ht-skrdy-hsnay", "סקרדי הסנאי", 2011, "הפקה מארכיון ערוץ הופ תמיר (2011–2013).", { kind: "series", endYear: 2013 }),
  prod("ht-lynks-abvd", "לינקס אבוד", 2026, "הפקה מארכיון ערוץ הופ תמיר (2026).", { kind: "series" }),
  // Featured: French Cupido (1991–92); Hebrew cast from ויקיפדיה / אישים. HT archive year was a placeholder.
  prod(
    "ht-kvpydv",
    "קופידו",
    1991,
    "סדרת אנימציה צרפתית (Cupido) על קופידון קטן בממלכת צבעוניה. שודרה בישראל בערוץ 2 ובחינוכית (1993–1994) בדיבוב עברי; ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      kind: "series",
      originalTitle: "Cupido",
      endYear: 1992,
      channel: "ערוץ 2 / חינוכית",
      genres: ["אנימציה", "ילדים", "דיבוב", "מדובב - זר"],
      imageUrl: portrait("קופידו", "Cupido"),
    }
  ),
  prod("ht-kvch-vydav", "כוח וידאו", 2026, "הפקה מארכיון ערוץ הופ תמיר (2026).", { kind: "series" }),
  prod("ht-bt-hym-hktnh", "בת הים הקטנה", 2026, "הפקה מארכיון ערוץ הופ תמיר (2026).", { kind: "series" }),
  prod("ht-sypvry-gdlyar", "סיפורי גדליער", 2026, "הפקה מארכיון ערוץ הופ תמיר (2026).", { kind: "series" }),
  prod("ht-sypvry-chyvt", "סיפורי חיות", 2000, "הפקה מארכיון ערוץ הופ תמיר (2000).", { kind: "series" }),
  prod("ht-hmchnh-hksvm", "המחנה הקסום", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "series" }),
  prod("ht-lasy", "לאסי", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014–2015).", { kind: "series", endYear: 2015 }),
  prod("ht-kptn-plmyngv", "קפטן פלמינגו", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006–2008).", { kind: "series", endYear: 2008 }),
  prod("ht-hkrvdym-mshpchh-chdshh", "הקרודים: משפחה חדשה", 2024, "הפקה מארכיון ערוץ הופ תמיר (2024).", { kind: "film" }),
  prod("ht-sndy-tz-yks-mtzylh-at-bykyny-bvtvm", "סנדי צ'יקס מצילה את ביקיני בוטום", 2024, "הפקה מארכיון ערוץ הופ תמיר (2024).", { kind: "series" }),
  prod("ht-sypvry-rpaym", "סיפורי רפאים", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-hvph-hyy-mashh-shhyh", "הופה היי - מעשה שהיה", 2011, "הפקה מארכיון ערוץ הופ תמיר (2011).", { kind: "series" }),
  prod("ht-lylv-vstytz", "לילו וסטיץ", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007–2008).", { kind: "series", endYear: 2008 }),
  prod("ht-dvrh", "דורה", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-batmn-aysh-hatlp", "באטמן - איש העטלף", 2005, "הפקה מארכיון ערוץ הופ תמיר (2005).", { kind: "series" }),
  prod("ht-avvtar-kshp-havvyr-hachrvn", "אווטאר: כשף האוויר האחרון", 2024, "הפקה מארכיון ערוץ הופ תמיר (2024).", { kind: "film" }),
  prod("ht-hkvl-brash-2", "הקול בראש 2", 2024, "הפקה מארכיון ערוץ הופ תמיר (2024).", { kind: "film" }),
  prod("ht-chbvrt-hkdvrgl-hprvah", "חבורת הכדורגל הפרועה", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-atvm-tzvvt-al-glglym", "אטום - צוות על גלגלים", 2005, "הפקה מארכיון ערוץ הופ תמיר (2005).", { kind: "series" }),
  prod("ht-zvbvmpv-vhachym-krat", "זובומפו והאחים קראט", 2026, "הפקה מארכיון ערוץ הופ תמיר (2026).", { kind: "series" }),
  prod("ht-svnyk-x", "סוניק X", 2004, "הפקה מארכיון ערוץ הופ תמיר (2004–2006).", { kind: "series", endYear: 2006 }),
  prod("ht-bratz", "בראץ", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006–2008).", { kind: "series", endYear: 2008 }),
  prod("ht-sypvry-shpt-hnchl", "סיפורי שפת הנחל", 2008, "הפקה מארכיון ערוץ הופ תמיר (2008).", { kind: "series" }),
  prod("ht-hmsa-hksvm-shl-aympy", "המסע הקסום של אימפי", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009).", { kind: "series" }),
  prod("ht-kvlr-nvld", "קולר נולד", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017).", { kind: "series" }),
  prod("ht-kvlr-nvld-tvbym-hshnyym", "קולר נולד: טובים השניים", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017).", { kind: "film" }),
  prod("ht-plvntr-lpny-shhkl-htchyl", "פלונטר: לפני שהכל התחיל", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017).", { kind: "film" }),
  prod("ht-plvntr-hsdrh", "פלונטר: הסדרה", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017–2020).", { kind: "film", endYear: 2020 }),
  prod("ht-tmyrvsh", "תמירוש", 2026, "הפקה מארכיון ערוץ הופ תמיר (2026).", { kind: "series" }),
  prod("ht-agdh-sh-mgdh", "אגדה ש'מגדה", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "series" }),
  prod("ht-zvtrvpvlys", "זוטרופוליס", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-bvbvbv-bv-bv-bvbv", "בובובו-בו בו-בובו", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "series" }),
  prod("ht-tvtly-spyys", "טוטלי ספייס", 2003, "הפקה מארכיון ערוץ הופ תמיר (2003–2014).", { kind: "series", endYear: 2014 }),
  prod("ht-ksm-shl-mshpchh", "קסם של משפחה", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009–2018).", { kind: "series", endYear: 2018 }),
  prod("ht-yv-gabh-gabh", "יו גאבה גאבה!", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009–2016).", { kind: "series", endYear: 2016 }),
  // Featured: שלושת ערכי «פרפר נחמד» מ־hoptamir-prods.json
  // (העונות הראשונות מיוצגות גם ב־parpar-nechmad ב־seed-wave2)
  prod(
    "ht-prpr-nchmd-late",
    "פרפר נחמד (העונות המאוחרות)",
    1998,
    "עונות מאוחרות של סדרת הילדים הקלאסית של הטלוויזיה החינוכית — מנחים ובובות (בץ, נולי, אוזה, שבי). ערך מתוך ארכיון ערוץ הופ תמיר (1998–2004).",
    {
      kind: "series",
      endYear: 2004,
      channel: "הטלוויזיה החינוכית / הופ תמיר",
      genres: ["ילדים", "ישראלי", "חינוכי", "בובות"],
      imageUrl: portrait("פרפר נחמד"),
    }
  ),
  prod(
    "ht-prpr-nchmd",
    "פרפר נחמד",
    2021,
    "חזרה מחודשת של סדרת הילדים הקלאסית (2021–2023). ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      kind: "series",
      endYear: 2023,
      channel: "הופ! / הופ תמיר",
      genres: ["ילדים", "ישראלי", "חינוכי", "בובות"],
      imageUrl: portrait("פרפר נחמד"),
    }
  ),
  prod("ht-hkvl-brash", "הקול בראש", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015).", { kind: "series" }),
  prod("ht-shpytzym", "שפיצים", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-mtvrllym", "מטורללים", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-hmabdh-shl-pvlka", "המעבדה של פולקע", 2011, "הפקה מארכיון ערוץ הופ תמיר (2011).", { kind: "series" }),
  prod("ht-kvkby-havr", "כוכבי האור", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-llkt-byn-dynvzavrym", "ללכת בין דינוזאורים", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-gybvry-havr-haychvd-hgdvl-atzmavt-2020", "גיבורי האור האיחוד הגדול עצמאות 2020", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020).", { kind: "film" }),
  prod("ht-mykl-hktnh-rvtzh-lhyvt-gdvlh", "מיכל הקטנה רוצה להיות גדולה", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012).", { kind: "series" }),
  prod("ht-chbvrt-mykl-hktnh", "חבורת מיכל הקטנה", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012).", { kind: "series" }),
  prod("ht-ksm-shl-dvd", "קסם של דוד", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-mykl-hktnh-vhtvntvnym", "מיכל הקטנה והטונטונים", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-chnvt-hsprym-shl-shyn-shyn", "חנות הספרים של שין שין", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-nty-hgaty-hvpaty", "נתי הגעתי הופעתי", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-bkvgn", "בקוגן", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009–2012).", { kind: "series", endYear: 2012 }),
  prod("ht-glgvlym", "גלגולים", 1995, "הפקה מארכיון ערוץ הופ תמיר (1995).", { kind: "series" }),
  prod("ht-my-shtvb-lv-vshmch-kp-ymcha-shyry-mshchk", "מי שטוב לו ושמח כף ימחא - שירי משחק", 1994, "הפקה מארכיון ערוץ הופ תמיר (1994).", { kind: "series" }),
  prod("ht-hdvb-bbyt-hkchvl", "הדוב בבית הכחול", 2000, "הפקה מארכיון ערוץ הופ תמיר (2000–2001).", { kind: "series", endYear: 2001 }),
  prod("ht-hdrk-lal-dvradv", "הדרך לאל-דוראדו", 2000, "הפקה מארכיון ערוץ הופ תמיר (2000).", { kind: "series" }),
  prod("ht-mgylt-astr", "מגילת אסתר", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-ymy", "ימי", 1996, "הפקה מארכיון ערוץ הופ תמיר (1996).", { kind: "series" }),
  prod("ht-atzbavt", "אצבעות", 1995, "הפקה מארכיון ערוץ הופ תמיר (1995).", { kind: "series" }),
  prod("ht-atzbavt-ly", "אצבעות לי", 2000, "הפקה מארכיון ערוץ הופ תמיר (2000).", { kind: "series" }),
  prod("ht-ayh-plvtv", "איה פלוטו", 1997, "הפקה מארכיון ערוץ הופ תמיר (1997).", { kind: "series" }),
  prod("ht-hmpvzr-mkpr-az-r", "המפוזר מכפר אז\\\"ר", 1997, "הפקה מארכיון ערוץ הופ תמיר (1997).", { kind: "series" }),
  prod("ht-rvy-bvy-yvtzaym-lhrptkh", "רוי בוי יוצאים להרפתקה", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-mglym-am-dvrh", "מגלים עם דורה", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006–2015).", { kind: "series", endYear: 2015 }),
  prod("ht-vvalas-vgrvmyt-vharnb-hktlny", "וואלאס וגרומיט והארנב הקטלני", 2005, "הפקה מארכיון ערוץ הופ תמיר (2005).", { kind: "series" }),
  prod("ht-srty-avgypltzt", "סרטי עוגיפלצת", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "film" }),
  prod("ht-hmkbym", "המכבים", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015).", { kind: "series" }),
  prod("ht-kvch-blagn", "כוח בלאגן", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-nsyk-mtzrym", "נסיך מצרים", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015).", { kind: "series" }),
  prod("ht-artvr", "ארתור", 1997, "הפקה מארכיון ערוץ הופ תמיר (1997–2022).", { kind: "series", endYear: 2022 }),
  prod("ht-tzvvt-4-hmvpla", "צוות 4 המופלא", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "film" }),
  prod("ht-mrth-mdbrt", "מרתה מדברת", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009–2012).", { kind: "series", endYear: 2012 }),
  prod("ht-sypvrym-shl-brvvzym", "סיפורים של ברווזים", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017–2021).", { kind: "series", endYear: 2021 }),
  prod("ht-drgvn-bvl", "דרגון בול", 2002, "הפקה מארכיון ערוץ הופ תמיר (2002).", { kind: "series" }),
  prod("ht-bg-vngl-shl-rvy-bvy", "בג'ונגל של רוי בוי", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012).", { kind: "series" }),
  prod("ht-mshmr-haryvt", "משמר האריות", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016–2020).", { kind: "series", endYear: 2020 }),
  prod("ht-mshmr-haryvt-hshagh-chvzrt", "משמר האריות - השאגה חוזרת", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-dvk-rvpat-tzatzvaym", "דוק רופאת צעצועים", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012–2019).", { kind: "series", endYear: 2019 }),
  prod("ht-trzn-vg-yyn", "טרזן וג'יין", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-lyrvy-vstytz", "לירוי וסטיץ", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-kym-pvsybvl-hsrt-kh-hdrmh", "קים פוסיבול הסרט: כה הדרמה", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "film" }),
  prod("ht-mprtz-hhrptkavt-hsrt", "מפרץ ההרפתקאות: הסרט", 2021, "הפקה מארכיון ערוץ הופ תמיר (2021).", { kind: "film" }),
  prod("ht-tym-glksy", "טים גלקסי", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "series" }),
  prod("ht-msbyb-lavlm-b-80-yvm", "מסביב לעולם ב-80 יום", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-shvrykn-skvl-byt-spr-lnyng-vt", "שוריקן סקול - בית ספר לנינג'ות", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "series" }),
  prod("ht-spyydrmn-lla-gbvlvt", "ספיידרמן ללא גבולות", 2000, "הפקה מארכיון ערוץ הופ תמיר (2000).", { kind: "series" }),
  prod("ht-g-ky-tz-an", "ג'קי צ'אן", 2002, "הפקה מארכיון ערוץ הופ תמיר (2002–2005).", { kind: "series", endYear: 2005 }),
  prod("ht-knpy-hram-bpavlh", "כנפי הרעם בפעולה", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015–2016).", { kind: "series", endYear: 2016 }),
  prod("ht-nyng-gv", "נינג'גו", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012–2017).", { kind: "series", endYear: 2017 }),
  prod("ht-glglym-lvhtym-nkvdt-prytzh", "גלגלים לוהטים - נקודת פריצה", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006).", { kind: "series" }),
  prod("ht-chbrym-ad-hshmyym", "חברים עד השמיים", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "series" }),
  prod("ht-mvmyvt", "מומיות", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-mvrys-hmdhym", "מוריס המדהים", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-hgdh-shl-kvkbym", "הגדה של כוכבים", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-g-yysvn-vhgybvrym", "ג'ייסון והגיבורים", 2002, "הפקה מארכיון ערוץ הופ תמיר (2002).", { kind: "series" }),
  prod("ht-shavlyn-vvzang", "שאולין ווזאנג", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "series" }),
  prod("ht-aydn-hkrch-2-nmsym-mtzchvk", "עידן הקרח 2: נמסים מצחוק", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006).", { kind: "film" }),
  prod("ht-aydn-hkrch-3-alyytm-shl-hdynvzavrym", "עידן הקרח 3: עלייתם של הדינוזאורים", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009).", { kind: "film" }),
  prod("ht-mshpcht-sympsvn-hsrt", "משפחת סימפסון - הסרט", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007).", { kind: "film" }),
  prod("ht-mtlvt-mvzrvt", "מטלות מוזרות", 2019, "הפקה מארכיון ערוץ הופ תמיר (2019–2022).", { kind: "series", endYear: 2022 }),
  prod("ht-plyymvbyl-hsrt", "פליימוביל הסרט", 2019, "הפקה מארכיון ערוץ הופ תמיר (2019).", { kind: "film" }),
  prod("ht-hmvpa-hmbvlbl-shl-yvbl", "המופע המבולבל של יובל", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017).", { kind: "series" }),
  prod("ht-hkl-agdh", "הכל אגדה", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-kdymh-ltyyl-bartz-yshral", "קדימה לטייל בארץ ישראל", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "series" }),
  prod("ht-gybvry-havr-mshymh-mhshkmh", "גיבורי האור - משימה מהשקמה", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015).", { kind: "series" }),
  prod("ht-myrh-blshyt-mlkvtyt", "מירה, בלשית מלכותית", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020–2023).", { kind: "series", endYear: 2023 }),
  prod("ht-gvrym-vchbrym", "גורים וחברים", 2018, "הפקה מארכיון ערוץ הופ תמיר (2018–2023).", { kind: "series", endYear: 2023 }),
  prod("ht-avtv-tvb", "אוטו טוב", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-nykv", "ניקו", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-rybyt", "ריביט", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-aydn-hkrch-4-ybsht-btnvah", "עידן הקרח 4: יבשת בתנועה", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012).", { kind: "film" }),
  prod("ht-aydn-hkrch-5-mslvl-htngshvt", "עידן הקרח 5: מסלול התנגשות", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "film" }),
  prod("ht-mshpcht-vylvby", "משפחת וילובי", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020).", { kind: "series" }),
  prod("ht-gynt-hshtvzym-shl-dtyh", "גינת השטוזים של דתיה", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006).", { kind: "series" }),
  prod("ht-mchsn-hshtvzym-shl-dtyh", "מחסן השטוזים של דתיה", 2000, "הפקה מארכיון ערוץ הופ תמיר (2000).", { kind: "series" }),
  prod("ht-pt-shvp-avlm-mshlnv", "פט שופ: עולם משלנו", 2019, "הפקה מארכיון ערוץ הופ תמיר (2019).", { kind: "film" }),
  prod("ht-bvbspvg-mknsmrvba-mtzyg-azvr-hgavt-vhshpl", "בובספוג מכנסמרובע מציג: אזור הגאות והשפל", 2023, "הפקה מארכיון ערוץ הופ תמיר (2023).", { kind: "film" }),
  prod("ht-hdrkvn-hmtvk-shly", "הדרקון המתוק שלי", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-hdrkvn-hmtvk-shly-2-hrptkh-msbyb-lavlm", "הדרקון המתוק שלי 2 - הרפתקה מסביב לעולם", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015).", { kind: "film" }),
  prod("ht-hgybvrym-mshymh-bg-vngl", "הגיבורים - משימה בג'ונגל", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-ba-ly-msybh-ly", "בא לי מסיבה לי", 1995, "הפקה מארכיון ערוץ הופ תמיר (1995).", { kind: "series" }),
  prod("ht-abyry-htnkay", "אבירי הטנקאי", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-gvldy-vhdb", "גולדי והדב", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016–2019).", { kind: "series", endYear: 2019 }),
  prod("ht-pvkymvn-myvtv-mkh-shnyt-htptchvt", "פוקימון: מיוטו מכה שנית - התפתחות", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020).", { kind: "film" }),
  prod("ht-pvkymvn-xy-hsdrh", "פוקימון XY: הסדרה", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016–2017).", { kind: "film", endYear: 2017 }),
  prod("ht-pvkymvn-hsdrh-shmsh-vyrch", "פוקימון הסדרה: שמש וירח", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017–2020).", { kind: "film", endYear: 2020 }),
  prod("ht-pvkymvn-msavt", "פוקימון: מסעות", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020–2023).", { kind: "film", endYear: 2023 }),
  prod("ht-tz-ak", "צ'אק", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-myrt-chvkrt", "מירט חוקרת", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017).", { kind: "series" }),
  prod("ht-tvrbv", "טורבו", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-tvrbv-tzvvt-pgz", "טורבו - צוות פגז", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015–2016).", { kind: "series", endYear: 2016 }),
  prod("ht-chyyzr-mchmd", "חייזר מחמד", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006–2007).", { kind: "series", endYear: 2007 }),
  prod("ht-chg-mvld-mdvrds", "חג מולד מדורדס", 2011, "הפקה מארכיון ערוץ הופ תמיר (2011).", { kind: "series" }),
  prod("ht-yn-yang-yv", "ין יאנג יו", 2007, "הפקה מארכיון ערוץ הופ תמיר (2007–2009).", { kind: "series", endYear: 2009 }),
  prod("ht-prykbvy-vtz-am-tz-am", "פריקבוי וצ'אם צ'אם", 2010, "הפקה מארכיון ערוץ הופ תמיר (2010–2012).", { kind: "series", endYear: 2012 }),
  prod("ht-kyd-vkat", "קיד וקאט", 2009, "הפקה מארכיון ערוץ הופ תמיר (2009–2011).", { kind: "series", endYear: 2011 }),
  prod("ht-havlympyadh-shl-hvp", "האולימפיאדה של הופ!", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016).", { kind: "series" }),
  prod("ht-gyyrmv-dl-tvrv-mtzyg-pynvkyv", "גיירמו דל טורו מציג: פינוקיו", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "film" }),
  prod("ht-chvky-hmrpy-shl-myylv", "חוקי המרפי של מיילו", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017–2019).", { kind: "series", endYear: 2019 }),
  prod("ht-pynvkyv", "פינוקיו", 2006, "הפקה מארכיון ערוץ הופ תמיר (2006).", { kind: "series" }),
  prod("ht-gas-habyr-hzayr", "גאס האביר הזעיר", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "series" }),
  prod("ht-mvrny-halvph", "מורני האלופה", 2015, "הפקה מארכיון ערוץ הופ תמיר (2015).", { kind: "series" }),
  prod("ht-aladyn-vysmyn", "אלאדין ויסמין", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-shlgyh-vhtzyyd", "שלגיה והצייד", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-nsyk-hagdvt", "נסיך האגדות", 2005, "הפקה מארכיון ערוץ הופ תמיר (2005).", { kind: "series" }),
  prod(
    "ht-kvpykv-bspryyh",
    "קופיקו בספרייה",
    2022,
    "ספין־אוף של «קופיקו»: קופיקו מקריא סיפורים בספרייה עם שומריקו ומיפו. שודרה בערוץ ג'וניור; ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      kind: "series",
      channel: "ערוץ ג'וניור",
      genres: ["ילדים", "ישראלי", "קומדיה", "בובות"],
      imageUrl: portrait("קופיקו בספרייה"),
    }
  ),
  prod("ht-bkvgn-kvkb-hkrb", "בקוגן: כוכב הקרב", 2019, "הפקה מארכיון ערוץ הופ תמיר (2019).", { kind: "film" }),
  prod("ht-ayny-myny-mv-mtyylym-bspr-hanglyt", "איני מיני מו מטיילים בספר האנגלית", 2008, "הפקה מארכיון ערוץ הופ תמיר (2008).", { kind: "series" }),
  prod("ht-pntzyh-alp-lylh-vlylh", "פנטזיה אלף לילה ולילה", 2014, "הפקה מארכיון ערוץ הופ תמיר (2014).", { kind: "series" }),
  prod("ht-yv-kay-vvtsh", "יו-קאי ווטש", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016–2019).", { kind: "series", endYear: 2019 }),
  prod("ht-dynvprvz", "דינופרוז", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013–2026).", { kind: "series", endYear: 2026 }),
  prod("ht-dvrh-vhayr-habvdh", "דורה והעיר האבודה", 2019, "הפקה מארכיון ערוץ הופ תמיר (2019).", { kind: "series" }),
  prod("ht-nchmd-la-nchmd", "נחמד, לא נחמד!", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "series" }),
  prod("ht-tly-vmvrn-yvatzvt-mkvkb-hagdvt", "טלי ומורן יועצות מכוכב האגדות", 2019, "הפקה מארכיון ערוץ הופ תמיר (2019).", { kind: "series" }),
  prod("ht-hmtrh-kdvrgl", "המטרה: כדורגל", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "film" }),
  prod("ht-shkchv-avty-bbyt", "שכחו אותי בבית", 2011, "הפקה מארכיון ערוץ הופ תמיר (2011).", { kind: "series" }),
  prod("ht-rvny-bvtz", "רוני בוץ", 2010, "הפקה מארכיון ערוץ הופ תמיר (2010).", { kind: "series" }),
  prod("ht-kvpt-hmlak", "קופת המלאך", 2010, "הפקה מארכיון ערוץ הופ תמיר (2010).", { kind: "series" }),
  prod("ht-rasty", "ראסטי", 2017, "הפקה מארכיון ערוץ הופ תמיר (2017–2019).", { kind: "series", endYear: 2019 }),
  prod(
    "ht-nchshvn-kl-ykvl",
    "נחשון כל יכול",
    2003,
    "סדרת ילדים ישראלית בערוץ הופ! בכיכוב אסף אשתר — ספין־אוף של «דפנה ודודידו». ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      kind: "series",
      endYear: 2004,
      channel: "ערוץ הופ!",
      genres: ["ילדים", "ישראלי", "חינוכי", "בובות"],
      imageUrl: portrait("נחשון כל יכול"),
    }
  ),
  prod("ht-byby-vtynh", "ביבי וטינה", 2012, "הפקה מארכיון ערוץ הופ תמיר (2012).", { kind: "series" }),
  prod("ht-grvb-hyy", "גרוב היי", 2013, "הפקה מארכיון ערוץ הופ תמיר (2013).", { kind: "series" }),
  prod("ht-ksm-shl-chg", "קסם של חג", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "series" }),
  prod("ht-skvvysh", "סקוויש", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020).", { kind: "series" }),
  prod("ht-avny-agdt-al-hram", "אוני: אגדת אל הרעם", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "film" }),
  prod("ht-pvkymvn-zvrvark-alvpt-hashlyvt", "פוקימון: זורוארק אלופת האשליות", 2011, "הפקה מארכיון ערוץ הופ תמיר (2011).", { kind: "film" }),
  prod("ht-sndrh-blshyt-mhagdvt", "סנדרה - בלשית מהאגדות", 2010, "הפקה מארכיון ערוץ הופ תמיר (2010).", { kind: "series" }),
  prod("ht-kayv", "קאיו", 2002, "הפקה מארכיון ערוץ הופ תמיר (2002–2013).", { kind: "series", endYear: 2013 }),
  prod("ht-kvny-haglh", "קוני העגלה", 2005, "הפקה מארכיון ערוץ הופ תמיר (2005).", { kind: "series" }),
  prod("ht-bags-bany-vchbrym", "באגס באני וחברים", 2016, "הפקה מארכיון ערוץ הופ תמיר (2016–2017).", { kind: "series", endYear: 2017 }),
  prod("ht-kvch-hmym", "כוח המים", 2004, "הפקה מארכיון ערוץ הופ תמיר (2004).", { kind: "series" }),
  prod("ht-kvch-htzlh", "כוח הצלה", 2004, "הפקה מארכיון ערוץ הופ תמיר (2004–2007).", { kind: "series", endYear: 2007 }),
  prod("ht-kvkv-harnb", "קוקו הארנב", 2008, "הפקה מארכיון ערוץ הופ תמיר (2008).", { kind: "series" }),
  prod("ht-magl-ktntnym", "מעגל קטנטנים", 2022, "הפקה מארכיון ערוץ הופ תמיר (2022).", { kind: "series" }),
  prod(
    "ht-chbvbvtp",
    "חבובוטף",
    2019,
    "ריבוט אנימציה ממוחשבת ל«חבובוטף» (Muppet Babies, 2018) — אנימציה של SnowBall בישראל; דיבוב עברי בדיסני ג'וניור. ערך מתוך ארכיון ערוץ הופ תמיר.",
    {
      kind: "series",
      originalTitle: "Muppet Babies",
      endYear: 2022,
      channel: "דיסני ג'וניור",
      genres: ["אנימציה", "ילדים", "דיבוב", "מדובב - זר"],
      imageUrl: portrait("חבובוטף", "Muppet Babies"),
    }
  ),
  prod("ht-ampybyh", "אמפיביה", 2020, "הפקה מארכיון ערוץ הופ תמיר (2020–2022).", { kind: "series", endYear: 2022 }),
];

/** Hop Tamir credits — פיטר פן מנוהל ב-seed-ishim-peter-pan.ts */
export const HOP_TAMIR_CREDITS: Credit[] = [
  // —— טימון ופומבה (אישים / הופ תמיר + ויקיפדיה) ——
  // Prefer existing main / wiki / ht person ids — no new people invented.
  { personId: "shafrira-zachai", productionId: "ht-tymvn-vpvmbh", role: "dub_director", characterName: "בימוי דיבוב" },
  { personId: "shafrira-zachai", productionId: "ht-tymvn-vpvmbh", role: "producer", characterName: "הפקת דיבוב" },
  { personId: "shafrira-zachai", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "שנזי" },
  { personId: "tomer-sharon", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "טימון" },
  { personId: "ami-mandelman", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "פומבה" },
  { personId: "shmvlyk-tna", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "בנזאי" },
  { personId: "ht-shmavn-khn", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "בנזאי / קווינט" },
  { personId: "chn-chgy", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "אד" },
  { personId: "alon-ofir", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "סימבה" },
  { personId: "avhd-shchr", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "זאזו" },
  { personId: "dov-reiber", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "ראפיקי" },
  { personId: "avi-hadash", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "דמויות שונות" },
  { personId: "yhvykyn-prydlndr", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "דמויות שונות" },
  { personId: "aprvn-atkyn", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "דמויות שונות" },
  { personId: "shrh-vynv-alad", productionId: "ht-tymvn-vpvmbh", role: "dubber", characterName: "דמויות שונות" },
  { personId: "ht-rvny-vyys", productionId: "ht-tymvn-vpvmbh", role: "composer", characterName: "ניהול מוזיקלי" },

  // —— היה היה - דואגים לכדור הארץ (ויקיפדיה העברית + הופ תמיר) ——
  { personId: "efi-ben-israel", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dub_director", characterName: "בימוי דיבוב" },
  { personId: "asf-ashtr", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber", characterName: "מאסטרו" },
  { personId: "liron-lev", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber", characterName: "פייר" },
  { personId: "lvrn-sbyr", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber", characterName: "סופי" },
  { personId: "gya-rvshynyak", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "avry-avmnvty", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "guy-friedman", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "abytl-abrgyl", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "aprt-gvsh", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "abytr-adyr", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "alh-ptr", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "michal-reshef", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },
  { personId: "doron-ben-ami", productionId: "ht-hyh-hyh-dvagym-lkdvr-hartz", role: "dubber" },

  // —— המומינים (ויקיפדיה העברית + הופ תמיר) ——
  { personId: "ht-chnh-drvry-kshy", productionId: "ht-hmvmywnym", role: "dub_director", characterName: "בימוי דיבוב" },
  { personId: "ht-chsyh-vrthyym", productionId: "ht-hmvmywnym", role: "producer", characterName: "הפקת דיבוב" },
  { personId: "yuval-segal", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינטרול" },
  { personId: "ht-yrvn-dgn", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינטרול" },
  { personId: "yonatan-hashiloni", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינטרול" },
  { personId: "ht-asf-khvly", productionId: "ht-hmvmywnym", role: "dubber", characterName: "סניף / סנורק" },
  { personId: "syvn-shbyt", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מאי הקטנה / בימבל / דינורה / המכשפה" },
  { personId: "ht-avdd-mnshh", productionId: "ht-hmvmywnym", role: "dubber", characterName: "סנופקין" },
  { personId: "amy-travb", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינאבא" },
  { personId: "ht-lylyan-brtv", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינאמא / סנורקה" },
  { personId: "ht-chny-nchmyas", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינאמא / סנורקה" },
  { personId: "ht-rvty-hvltzmn", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינאמא" },
  { personId: "rama-messinger", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מומינאמא" },
  { personId: "ht-ayrys-zyngr", productionId: "ht-hmvmywnym", role: "dubber", characterName: "סנורקה" },
  { personId: "ht-avrnh-lbya-plynt", productionId: "ht-hmvmywnym", role: "dubber", characterName: "גב' פיליונק / אליסיה / סנורקה" },
  { personId: "dn-tvrn", productionId: "ht-hmvmywnym", role: "dubber", characterName: "סנופקין / המפקח / סרח / המספר" },
  { personId: "ht-shmavn-khn", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מר המיולין" },
  { personId: "avi-hadash", productionId: "ht-hmvmywnym", role: "dubber", characterName: "מספר / ארינמל" },

  // —— פרפר נחמד — העונות המאוחרות (1998–2004) / ויקיפדיה + הופ תמיר ——
  { personId: "dudu-zar", productionId: "ht-prpr-nchmd-late", role: "host", characterName: "מנחה" },
  { personId: "efi-ben-israel", productionId: "ht-prpr-nchmd-late", role: "host", characterName: "מנחה" },
  { personId: "guy-friedman", productionId: "ht-prpr-nchmd-late", role: "host", characterName: "מנחה" },
  { personId: "elinor-aharon", productionId: "ht-prpr-nchmd-late", role: "host", characterName: "מנחה" },
  { personId: "adva-adani", productionId: "ht-prpr-nchmd-late", role: "host", characterName: "מנחה אורחת" },
  { personId: "rama-messinger", productionId: "ht-prpr-nchmd-late", role: "actor", characterName: "אורחת" },
  { personId: "ami-weinberg", productionId: "ht-prpr-nchmd-late", role: "dubber", characterName: "בץ" },
  { personId: "ayelet-levin", productionId: "ht-prpr-nchmd-late", role: "dubber", characterName: "נולי" },
  { personId: "irit-shilo", productionId: "ht-prpr-nchmd-late", role: "dubber", characterName: "אוזה" },
  { personId: "avi-yakir", productionId: "ht-prpr-nchmd-late", role: "dubber", characterName: "שבי" },
  { personId: "itzik-geyer", productionId: "ht-prpr-nchmd-late", role: "dubber", characterName: "דמויות / בובות" },
  { personId: "drvr-krn", productionId: "ht-prpr-nchmd-late", role: "actor", characterName: "אורח" },
  { personId: "gylyh-shtrn", productionId: "ht-prpr-nchmd-late", role: "actor", characterName: "אורחת" },

  // —— פרפר נחמד — חזרה כאן חינוכית (2021–2023) ——
  { personId: "mshy-klynshtyyn", productionId: "ht-prpr-nchmd", role: "host", characterName: "מנחה" },
  { personId: "ami-weinberg", productionId: "ht-prpr-nchmd", role: "dubber", characterName: "בץ" },
  { personId: "ayelet-levin", productionId: "ht-prpr-nchmd", role: "dubber", characterName: "נולי" },
  { personId: "gilles-ben-david", productionId: "ht-prpr-nchmd", role: "dubber", characterName: "שבי" },
  { personId: "tly-bn-yvsf", productionId: "ht-prpr-nchmd", role: "dubber", characterName: "הפרפר הנחמד" },

  // —— קופידו (ויקיפדיה העברית + אישים) ——
  { personId: "yaffa-gabay", productionId: "ht-kvpydv", role: "dubber", characterName: "קופידו" },
  { personId: "avhd-shchr", productionId: "ht-kvpydv", role: "dubber" },
  { personId: "ht-rvty-hvltzmn", productionId: "ht-kvpydv", role: "dubber" },
  { personId: "rvnn-gvldprb", productionId: "ht-kvpydv", role: "dubber", characterName: "מר צהוב" },
  { personId: "ahrvn-kpln", productionId: "ht-kvpydv", role: "dubber" },
  { personId: "avryt-amyr", productionId: "ht-kvpydv", role: "dubber" },
  { personId: "shy-kvkvy", productionId: "ht-kvpydv", role: "dubber" },

  // —— קופיקו בספרייה (ויקיפדיה העברית) ——
  { personId: "lyavr-dtavkr", productionId: "ht-kvpykv-bspryyh", role: "dubber", characterName: "קופיקו" },
  { personId: "avral-tsbry", productionId: "ht-kvpykv-bspryyh", role: "actor", characterName: "שומריקו" },
  { personId: "hila-shlagel", productionId: "ht-kvpykv-bspryyh", role: "actor", characterName: "מיפו" },

  // —— נחשון כל יכול (ויקיפדיה העברית) ——
  { personId: "asf-ashtr", productionId: "ht-nchshvn-kl-ykvl", role: "actor", characterName: "נחשון / כפפת המחשבות" },
  { personId: "ht-shmavn-khn", productionId: "ht-nchshvn-kl-ykvl", role: "dubber", characterName: "ויקטור" },
  { personId: "sharon-bar-ezer", productionId: "ht-nchshvn-kl-ykvl", role: "dubber", characterName: "חבובה" },

  // —— חבובוטף (ריבוט 2018 / ויקיפדיה העברית) ——
  { personId: "tsvika-furman", productionId: "ht-chbvbvtp", role: "dubber", characterName: "קרמיט הצפרדע" },
  { personId: "tzili-yenko", productionId: "ht-chbvbvtp", role: "dubber", characterName: "מיס פיגי" },
  { personId: "yuval-garbash", productionId: "ht-chbvbvtp", role: "dubber", characterName: "פוזי הדוב" },
  { personId: "simcha-barbiro", productionId: "ht-chbvbvtp", role: "dubber", characterName: "גונזו" },
  { personId: "aytn-grynbrg", productionId: "ht-chbvbvtp", role: "dubber", characterName: "אנימל" },
  { personId: "alona-alexander", productionId: "ht-chbvbvtp", role: "dubber", characterName: "סאמר" },
  { personId: "mona-mor", productionId: "ht-chbvbvtp", role: "dubber", characterName: "נני" },
  { personId: "eran-mor", productionId: "ht-chbvbvtp", role: "dubber", characterName: "סטטלר" },
  { personId: "gadi-levi", productionId: "ht-chbvbvtp", role: "dubber", characterName: "וולדורף" },
];
